### PR TITLE
XProc harness for BaseX server

### PR DESCRIPTION
**Pull request by AirQuick**
XProc harness for BaseX server (`src/harnesses/basex/basex-server-xquery-harness.xproc`) was first introduced in v0.4 RC and backed out later. (I guess it never worked.)
This pull request reinstates it and fixes it.

### Test
* Commit: 387e3d00f4524f26c015857590a06271a1ee249e
* Result: [Travis](https://travis-ci.org/AirQuick/xspec/jobs/536945551#L1707), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/24797703/job/etjalgigpg59qw54#L319)

### Further work
Update [Wiki](https://github.com/xspec/xspec/wiki/Running-with-BaseX), based on the test

### CODE REVIEW

**Comment by AirQuick** [comment]
Thanks @cirulls for reviewing this, especially helpful as I'm not familiar with BaseX at all.

Right. There will be no conflict. Can you merge this at your convenience?

For documentation, I filed #578 as a reminder.

**Comment by cirulls** [comment]
@AirQuick: I merged this PR into `master`.

**Comment by galtm** [comment]
@AirQuick  or @cirulls : I recently started having trouble with `run-bats.cmd` case 35 when I try to run the test suite locally on Windows 10. I updated my Calabash version to the one listed in `appveyor.yaml` (1.1.23-98), but that didn't help. Here's the output I am seeing.

```
CASE #35: XProc harness for BaseX (server)
The system cannot find the path specified.
...:run @ 13:08:06.63: java -jar "H:\Documents\github_xspec\downloads_for_running_test_suite\xmlcalabash-1.1.23-98\xmlcalabash-1.1.23-98.jar"         -i source=../tutorial/xquery-tutorial.xspec         -p xspec-home="file:/H:/Documents/github_xspec/xspec/"         -p endpoint=http://localhost:8984/rest         -p username=admin         -p password=admin         -p auth-method=Basic         -o result="file:/C:/Users/galtm/AppData/Local/Temp/run-bats~TEMP~_work/xquery-tutorial-result.html"         ..\src\harnesses\basex\basex-server-xquery-harness.xproc
...FAIL: Return value is 1. Expected 0.
---------- "C:\Users\galtm\AppData\Local\Temp\run-bats~TEMP~_work\run_raw.log"
ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
ERROR:     cause: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
ERROR: Underlying exception: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
----------
...FAIL: Line count 4 does not match the expected count 1
---------- "C:\Users\galtm\AppData\Local\Temp\run-bats~TEMP~_work\run_linenum.log"
[1]ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[2]ERROR:     cause: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[3]ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[4]ERROR: Underlying exception: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
----------
...FAIL: Line 1 does not match the expected string
---------- "C:\Users\galtm\AppData\Local\Temp\run-bats~TEMP~_work\run_linenum.log"
[1]ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[2]ERROR:     cause: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[3]ERROR: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
[4]ERROR: Underlying exception: Connect to localhost:8984 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
----------
...FAIL: Not exist: C:\Users\galtm\AppData\Local\Temp\run-bats~TEMP~_work/xquery-tutorial-result.html
The system cannot find the path specified.
```

My guess is that it's not a bug, but rather something wrong with my environment. Do you know what the problem is? Thanks!

**Comment by AirQuick** [comment]
Probably you didn't extract the whole content of BaseX's zip file. The `XProc harness for BaseX (server)` test uses not only `BaseX.jar` but also the other files in BaseX's zip file. i.e. If you have `BASEX_JAR=C:\foo\BaseX.jar`, `C:\foo\bin\basexhttp.bat` and other files should exist.
I forgot to update [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) about that.

**Comment by cirulls** [comment]
In the wiki page [How to Run the Test Suite Locally](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) there is a mention of downloading the whole zip file:

> When available, it it recommended to download and extract the full zip files rather than just the .jar file as there are often additional dependencies.

However, in the wiki page [Running with BaseX](https://github.com/xspec/xspec/wiki/Running-with-BaseX) only the .jar file is mentioned:

> Download the .jar file of BaseX (BaseX 8.6.4 is used here) and store it in a local directory (e.g. ~/xml/basex for Linux/MacOS or C:\basex for Windows).

@galtm: could you test if the solution suggested by @AirQuick fixes your local configuration? It would be useful for other contributors so that we can update the relevant wiki pages.

**Comment by galtm** [comment]
@AirQuick  and @cirulls : Thanks a lot for your quick replies. Extracting the entire ZIP-file for BaseX solved the problem. I'm not sure why I didn't extract the whole ZIP-file when I first set things up.

**Comment by cirulls** [comment]
Good that you came across this issue, it reminded us to update the BaseX configuration.

**Pull request merged**
