### PR TITLE
Fix Schematron temporary context file location

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #321. So needs to be handled after that.

---

Invoking `xspec.sh -s` with `TEST_DIR` specified creates temporary `context-*.xml` files in another location.

The problem is twofold:
* `xspec.sh` does not set `test_dir` parameter for `schut-to-xspec.xsl`
* `schut-to-xspec.xsl` sets relative URI for `xsl:result-document`

This pull request fixes it:

* 3b177c0fef6866a382e60a79bdf0526367407920 reproduces the problem. ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/423637263#L1450-L1482))
* 8a257e99ef6da2e093bc9f6ff220a3dc8bb08ee7 fixes the problem.

### CODE REVIEW

**Comment by AirQuick** [comment]
Although this pull request contains a lot of commits for historical reasons, all that needs to be reviewed in the end is this pair of commits:
> * 3b177c0 reproduces the problem. ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/423637263#L1450-L1482))
> * 8a257e9 fixes the problem.

**Comment by cmarchand** [comment]
Not a big deal for that. I've comment my code with a FIXME for this. Is it plan for 1.2 Release ?

Thanks for the warning.

**Comment by AirQuick** [comment]
Not scheduled to be included in the upcoming v1.2.0.
Will be merged into master soon after releasing v1.2.0, provided that no concern arises.

**Comment by AirQuick** [comment]
@cirulls 
Merged this bug fix.

**Pull request merged**
