### PR TITLE
feat: also accept 'schematron', 'xquery', or 'xslt' for Ant 'test.type'

### PR DESCRIPTION
**Pull request by tgraham-antenna**
's', 'q', and 't' aren't particularly informative, IMO.  Also there's typically less need to save keystrokes if you're going to repeatedly run the same Ant build file.

This PR lets `${test.type}` alternatively be the long form of the type name, matched case-insensitively.

### CODE REVIEW

**Comment by AirQuick** [comment]
The primary change (a84680b63dc9ba3cffd36bb124eae1c5965e42aa) looks useful and good to me.

The test (9261979d7366fac03d49d6e3011b145a887fbfa3) is clever. But it highly depends on the sequence order of [`collection()`](https://github.com/xspec/xspec/blob/9261979d7366fac03d49d6e3011b145a887fbfa3/test/ant/worker/generate.xsl#L56-L57). The test may fail unexpectedly, which actually [happened on AppVeyor](https://ci.appveyor.com/project/xspec/xspec/builds/27474451). The test could succeed unexpectedly, if a84680b63dc9ba3cffd36bb124eae1c5965e42aa were erroneous in a way disguised by the first document in the sequence.
Also, as noted in [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally#bats-tests), testing the interface parameters are not the scope of **XSpec tests**.

So I'd suggest moving the test to **Bats tests** where the interface parameters are tested. You have to write the test for two platforms ([`test/xspec.bats`](https://github.com/xspec/xspec/blob/master/test/xspec.bats) for *nix and [`test/win-bats/collection.xml`](https://github.com/xspec/xspec/blob/master/test/win-bats/collection.xml) for Windows) eventually, but you can basically copy each other. If right now you can write only for one platform, that's ok. I'll be happy to copy it to the other platform on your behalf.

**Comment by AirQuick** [comment]
@tgraham-antenna 
I pushed some Bats tests directly to this branch: dc4831cee5026c245900d67382b874d0aa23bd09
Is that fine with you? If so, I think we can revert 9261979d7366fac03d49d6e3011b145a887fbfa3 and merge this pr.

**Comment by AirQuick** [comment]
> ... If so, I think we can revert [9261979](https://github.com/xspec/xspec/commit/9261979d7366fac03d49d6e3011b145a887fbfa3) ...

Done it and merged the current `master` on your behalf.

**Comment by tgraham-antenna** [comment]
It looks fine to me, thank you.

**Comment by AirQuick** [comment]
Thanks, @tgraham-antenna 

Merged this and updated [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant#useful-properties) to to reflect it. ([diff](https://github.com/xspec/xspec/wiki/Running-with-Ant/_compare/d621ed4b4f6f2bdb99bb2ca10a7525a731f34964...1815e9685b2c6b66c21f96b43f344b90d2574927))

**Pull request merged**
