### PR TITLE
Add Ant build support for code coverage

### LINKED ISSUE #147: Oxygen Harmonization: Code Coverage
Code coverage requires Saxon PE or EE features; however, for many of us our access to those features are as part of the license we get in Oxygen.

Therefore we need to be able to access the code coverage features through the oxygen framework version of XSpec.

This should be possible by supplying Jeni's coverage class as a library to the XSpec transformation (possibly adding a target or property to the build.xml)

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #269. So needs to be handled after that.

---

Closes #147

This pull request allows to generate the code coverage report using Ant build script.
The new property `xspec.coverage.enabled` controls that. (default `false`)

#### Command line

1. Clone this pull request.
1. Just add `-Dxspec.coverage.enabled=true` to your usual command line. For example,
    ```
    ant -buildfile /path/to/xspec/build.xml -lib /path/to/saxon-ee.jar -Dxspec.xml=/path/to/your.xspec -Dxspec.coverage.enabled=true
    ```
    ==> `*-coverage.html` will be generated in the `xspec` subdirectory.

#### Oxygen

1. Clone this pull request. For example, clone it into `/test/xspec/`.
1. In Oxygen, open your `.xspec` file.
1. In the **Transformation Scenarios** pane, duplicate **Run XSpec Test**.
1. In the **Options** tab of **Edit Ant Scenario** dialog, specify `/test/xspec/` in **Working directory**.
1. In the **Parameters** tab, set `xspec.project.dir` = `/test/xspec/`
1. Click **New** in the **Parameters** tab and add `xspec.coverage.enabled` = `true`.
1. Click **New** in the **Parameters** tab and add `xspec.coverage.html` = `${cfd}/${cfn}-coverage.html`.
1. In the **Output** tab, set `${cfd}/${cfn}-coverage.html` in **Open**.
1. Click **OK** to close the **Edit Ant Scenario** dialog.
1. Apply the new duplicated transformation scenario.
    ==> XSpec Ant begins collecting code coverage. Oxygen will open the coverage report in your default browser.

### Test

Using the files in #197, I manually verified that this pull request generated the same HTML file as the current master.

No automated tests for now. It should be addressed by #195.

### Further work

* Document `xspec.coverage.enabled` in [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant).
    (`xspec.coverage.html` should be kept undocumented unless `xspec.result.html` is documented...)

### CODE REVIEW

**Comment by AirQuick** [comment]
Although labelled as `enhancement`, this PR is actually required for testing. The following tests depend on this PR.
* *Regression test for code coverage* (#326)
* *Test code coverage report files (as well as XML, HTML and JUnit)* (#341)
* *Fix issue 214 (coverage-report.xsl fails to parse CDATA)* (#342)

So, in short, I hope this PR get merged asap and move forward :)

**Comment by AirQuick** [comment]
@yamahito
This will close #147. Please let us know if you have a concern.

**Comment by cirulls** [comment]
@AirQuick: this is the next pull request to review on my list. I'll try to review by the end of this week, please bear with me for few days.

**Comment by cirulls** [comment]
@AirQuick: I tried to run it on the command line and on oXygen but I got inconsistent coverage reports, I'm not sure if it is an issue in my configuration and want to double check with you first. 

**Command line**
Environment: Linux
Shell: bash
Ant version: 1.9.6
Saxon EE: 9.7
Command:
```bash
ant -buildfile build.xml -lib /home/cirulls/Documents/programming/saxon-9ee/saxon9ee.jar -Dxspec.xml=tutorial/escape-for-regex.xspec -Dxspec.coverage.enabled=true
```

I get this coverage report:

image

This is what I expected and it's the same coverage report I would get via xspec.sh -c. So far so good.

**oXygen**
oXygen version: 20.0
Ant version: 1.9.8 (default on oXygen 20.0)
Saxon EE: 9.8.0.8 (default on oXygen 20.0)

I followed your instructions for setting the transformation scenario, here is my setting:

image

image

image

However, I get a different coverage report:

image

I would expect the same report but instead I get no missing target (i.e. nothing is highlighted in red). 

Could you double check if you get the same report at your end? 

I initially suspected that Saxon EE was not picked up in my transformation scenario settings but a) I could not see any option in the transformation scenario to specify which Saxon processor to use; b) I would expect the transformation scenario to fail in case Saxon HE is used by default.   

Can you see any obvious mistake on my oXygen settings? Could you share your configuration?

**Comment by AirQuick** [comment]
That difference comes from the Saxon version difference.
Using the current master + command line, Saxon 9.6 and 9.8 behave differently in the same way as you found. It's my impression that the 9.8 output (and your oXygen output) is correct.

**Comment by AirQuick** [comment]
And that's why I filed #196, submitted #197 (now #299) and used the files in it for testing this pull request.

**Comment by cirulls** [comment]
Thanks for your comments, it makes sense now. I tried the same with the tutorial files for code coverage you committed in #299 and I got identical code coverage reports on both the command line and oXygen 20.0 so this is good. 

I'll finish off my review and keep you posted, I expect to merge this soon into `master`.

**Comment by AirQuick** [comment]
> Document xspec.coverage.enabled in Wiki.

Done:
* [Running with Ant](https://github.com/xspec/xspec/wiki/Running-with-Ant/_compare/ca682d005a76225f121437fabb91b15ca072423e...72e9c7abae547e8f3744b9caabcf5890210632f0)
* [Code Coverage](https://github.com/xspec/xspec/wiki/Code-Coverage/_compare/3d9b810236ba2728abebd652988fcfb1221b7928...34fcb1b7327166f825bbf03e3ec20c982785efb9)

**Comment by cirulls** [comment]
Looks good, thanks for updating the documentation.

**Pull request merged**
