### PR TITLE
Moved threshold that hides result & expect as param

### PR DESCRIPTION
**Pull request by cmarchand**
Talk in issue #398

### CODE REVIEW

**Comment by cirulls** [comment]
Thanks for this pull request. I had to rerun the test suite on AppVeyor as there was a [timeout error in downloading ant for Windows](https://ci.appveyor.com/project/xspec/xspec/builds/19427671/job/xn0k8y2vwj92441p#L56), everything is green now. 

@cmarchand: is this fine if we review and possibly merge this pull request into the v1.2.0 release or do you absolutely need it for v1.1.0 (which I'm going to release by the end of this week) and the maven plugin?
@AirQuick : would you be willing to review this pull request? So that I can focus solely on your many open pull requests 😉

**Comment by AirQuick** [comment]
I will, but I think this issue should be handled after merging #365 which tests the feature in question.

**Comment by cmarchand** [comment]
I can wait for 1.2.0.

**Comment by cmarchand** [comment]
This pull request must be completed to send parameter from build.xml and other run scripts. So do not merge it now.

**Comment by AirQuick** [comment]
#1500 supersedes this pull request.

**Pull request closed without merging**
