### PR TITLE
Schema: Add as? to global-param

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #349. So needs to be handled after that.

---

In the current schema, `as?` is missing from `global-param`.
So `/x:description/x:param/@as` is rejected without reason. ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/426596911#L1467-L1470), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/build/1227-fix_global-param-as/job/79bdnppjpufhgv64#L363))

This pull request fixes it.

### CODE REVIEW

**Comment by AirQuick** [comment]
@galtm 
This change isn't related directly to #475 but this pull request is [mentioned there](https://github.com/xspec/xspec/pull/475#discussion_r242156551).
So this review request is more like a FYI than a serious request. Just a glance at [the change](https://github.com/xspec/xspec/compare/bab2b036b8194914c3df2a92ebfc6c326f70aa90...560808f8c936d6e250acc0cf723817cf6f7ce7c8) would be enough.

**Comment by galtm** [comment]
> This change isn't related directly to #475 but this pull request is [mentioned there](https://github.com/xspec/xspec/pull/475#discussion_r242156551).

I'm inclined to remove my "Check effect of `@as` in XSLT" scenario from `xspec-variable_stylesheet.xspec` in my PR#475 and add code to xspec-param-as.xspec, to keep all the `@as` testing in one place. Do you agree?

**Comment by AirQuick** [comment]
> keep all the `@as` testing in one place

Yes, that would be greatly appreciated.

**Comment by AirQuick** [comment]
Thanks, @galtm.

@cirulls 
Merged this bug fix.

**Comment by galtm** [comment]
> > keep all the `@as` testing in one place
> 
> Yes, that would be greatly appreciated.

I just uploaded ca919137fc4ed1e8e64d99028ddb800a38c6caac.

**Pull request merged**
