### PR TITLE
Test with Saxon 9.8.0.14 (and other minor changes)

### PR DESCRIPTION
**Pull request by AirQuick**
This PR moves Saxon 9.8 and XML Calabash forward to the latest maintenance release.

Accompanied are other minor changes:
* Comments in Ant helpers
* A minor improvement of the batch script
* Fix of a URL in a comment
* Fix of typo

### CODE REVIEW

**Comment by AirQuick** [comment]
@vincentml 
Could you review this? It's just a collection of small changes which I hope will not be a burden on you.

The latest Saxon version is 9.8.0-**11**, but somehow it is [not available](http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/). 9.8.0-**10** has a nasty [bug](https://saxonica.plan.io/issues/3722). So I think we can stay on 9.8.0-**8** at the moment.

**Comment by vincentml** [comment]
@AirQuick I'm happy to do the review for this pull request. It might be a few days until I have time.

**Comment by AirQuick** [comment]
> The latest Saxon version is 9.8.0-11, but somehow it is not available. 9.8.0-10 has a nasty bug. So I think we can stay on 9.8.0-8 at the moment.

Now that 9.8.0-12 is available, I've updated this pull request to reflect it.

**Comment by AirQuick** [comment]
Obsoleted by #271 - #278.

**Pull request closed without merging**
