### PR TITLE
Improvements to HTML report

### PR DESCRIPTION
**Pull request by vincentml**
This is a set of minor improvements to the HTML report:

* Include CSS inline (as suggested in pull request #111)
* Include success/fail/pending images from oXygen (as suggested in issue #92)
* HTML report is one file with no dependencies for portability (as suggested in pull request #111)
* Right align edges to improve formatting
* Reduce body margins to improve formatting
* Remove auto-capitalization of scenario labels to improve readability
* Improve display of passed / pending / failed / total counts (issue #92)

### CODE REVIEW

**Comment by AirQuick** [comment]
Wondering if `@doe` works nicely with XProc. Following the current [doc](https://github.com/xspec/xspec/wiki/Running-with-XProc) with this CSS
```css
body > h1::after {
	content: "Pride & Prejudice";
}
```
, I got this `<style>` in the report HTML:
```html
body &gt; h1::after {&#xD;
	content: "Pride &amp; Prejudice";&#xD;
}&#xD;
```

**Comment by vincentml** [comment]
I'm not sure if there is a way to get XProc to play nicely with @disable-output-escaping. For now, I have added a parameter to the report XSLT so that CSS can be included inline by xspex.bat and xspec.sh, and default to the current behavior of referencing the CSS file for XProx/other environments.

**Comment by vincentml** [comment]
Hi @cirulls 

Have you had a chance to look at this pull request? 

I think the new end to end test will need an update with this pull request. First, the regex at [_normalizer.xsl#L50](https://github.com/xspec/xspec/blob/40316746f67e9382f434e446cd4f1a12c210c938/test/end-to-end/processor/_normalizer.xsl#L50) should be changed to 

`regex="^(Test Report for) (.+) (\([a-z0-9/: ]+\))$"`

and then generate-expected.sh (or .cmd) will need to be run as described in [xspec/test/end-to-end/README.md](xspec/test/end-to-end/README.md)

**Comment by cirulls** [comment]
Sorry, I haven't yet had the chance to review this pull request, I'll try to have a look at it this week. Thanks for the suggestion about the end-to-end test, I'll have a look at this as well.

**Comment by AirQuick** [comment]
> I think the new end to end test will need an update with this pull request.

I'll merge master into here and do that for convenience.

**Comment by vincentml** [comment]
Thanks @AirQuick !

**Pull request merged**
