### PR TITLE
build: release v2.3.2

### PR DESCRIPTION
**Pull request by galtm**
This pull request is for the checklist item in #1657 that says, "Create a pull request incrementing the version (to `2.3` without `-SNAPSHOT`) of `pom.xml` and the Oxygen add-on and merge it into `master`".

It increments the version numbers to make the official stable release of v2.3. (technically v2.3.2, based on https://github.com/xspec/xspec/issues/940).

I tested the Oxygen add-on in Oxygen 25.1 using https://github.com/galtm/xspec/raw/rel_2-3-2/oxygen-addon.xml.

### CODE REVIEW

**Comment by galtm** [comment]
@AirQuick and @cmarchand , I'll wait until the end of the weekend to see if you have time to do a code review. That seems lower risk than merging this PR prematurely, in case I made a mistake somewhere.

**Review by AirQuick — APPROVED** [review]
Looks good to me. Thanks for managing this release!

**Comment by galtm** [comment]
Thanks for your review, @AirQuick ! I'm merging this. I will verify the add-on online and monitor the Maven deployment.

**Comment by galtm** [comment]
> I will verify the add-on online and monitor the Maven deployment.

The upgrade from the add-on v2.3.1 was offered and v2.3.2 is working as expected in Oxygen 25.1.

The [Maven deployment log](https://github.com/xspec/xspec/actions/runs/6373637716/job/17297527970) looks successful. The log includes the following sample upload info and build success message:
```
[INFO] Uploaded to xspec-io.ossrh: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/ioxspec-1037/io/xspec/xspec/2.3.2/xspec-2.3.2-enduser-files.zip(https://oss.sonatype.org/service/local/staging/deployByRepositoryId/ioxspec-1037/io/xspec/xspec/2.3.2/xspec-2.3.2-enduser-files.zip) (269 kB at 453 kB/s)

...

[INFO] Remote staging repositories released.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

I see artifacts for v2.3.2 at https://repo1.maven.org/maven2/io/xspec/xspec/2.3.2/ .

I updated a sample pom.xml file in my local workspace by changing `<version>2.2.4</version>` to ` <version>2.3.2</version>` for the xspec artifact, and the command `mvn clean test` succeeds.

**Pull request merged**
