### PR TITLE
Revert to commit f4811a5 as tests are failing on master #97

### PR DESCRIPTION
**Pull request by cirulls**
## Summary 
This pull request reverts to commit f4811a5 in order to have green tests on master (they are currently red).

## Why
Please see discussion in #97.

## What has changed
I reverted ```generate-xspec-tests.xsl``` to the previous version.

@AirQuick and @fgeorges : could you please review it? This is just a temporary change to make the test suite green on master. Any new pull request to address #99 is very welcome.

### CODE REVIEW

**Comment by cirulls** [comment]
@AirQuick : thanks for reviewing it. 
@fgeorges : it would to get your feedback within 24/36 hours so that we don't keep the master branch's badge red for long:

image

Or even better, feel free to submit a pull request with the implementation of attributes ```assert``` and ```context``` that does not break the current test suite on Travis and AppVeyor so that my pull request can be overridden by yours.

**Comment by cirulls** [comment]
@fgeorges : it would be good if you can reply to this so that we can get the test builds back to green or submit a pull request for attributes ```assert``` and ```context``` to will make the broken tests pass. My priority right now is to get things back to green.

**Comment by fgeorges** [comment]
Never saw your question, just came here by chance.  Next time please at least send me an email.  I am working on getting them fixed.  I don't think we should be obsessed by "being green" (especially not trying to solve it by reverting some files back when what started the whole thing was reverting some files back).

I made a mistake by pushing to `master`, my apologies.  I am fixing it.

**Comment by AirQuick** [comment]
Well, at least I now understand how v0.4 RC was born...

**Comment by cirulls** [comment]
>  Next time please at least send me an email.

@fgeorges, you can subscribe to the GitHub notifications for the XSpec repository so that you can automatically get emails when someone mentions you or comment on an issue or pull request you initiated. Just click on the Watch button on https://github.com/xspec/xspec and make sure you have email ticked in https://github.com/settings/notifications

**Comment by fgeorges** [comment]
Thank you, @cirulls.  I get them now (and got at least some of the previous one actually).  I must admit I get hundreds of emails a day, and automatic emails tend to fly sometimes below my radar.  I'll try to be more careful about Github notifications from XSpec ;-)

**Pull request merged**
