### PR TITLE
Deprecation warning for Saxon 9.7 or less

### PR DESCRIPTION
**Pull request by AirQuick**
See #596. This pull request prints a deprecation warning message at compile time if Saxon version is 9.7 or less.

On 9.7:

```console
F:\xspec>bin\xspec.bat tutorial\escape-for-regex.xspec
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...
WARNING: Saxon version 9.7 or less is deprecated. XSpec will stop supporting it in the near future.

Running Tests...
Testing with SAXON HE 9.7.0.21
...
```

On 9.8 or later:

```console
F:\xspec>bin\xspec.bat tutorial\escape-for-regex.xspec
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...


Running Tests...
Testing with SAXON HE 9.8.0.12
...
```

### Commits

* 719351d029ae78d035ffa8890357450899e28fa2 implements utility functions to handle version information.
* ec1b3344bb22cc0645823cb6e2b01c8085b0d065 implements the deprecation warning message.
* ca99bec98d9b78d1f8b0d76c467c39c34e14d7a0 tests the deprecation warning message.
* 2b859d7b2a2f6c4127c81e5fc369d07b72d5ecb4 updates a test driver so that a test is skipped on Saxon 9.7 because of its known bug (details: https://github.com/xspec/xspec/pull/586#issue-303158130).
* c69aae245b1ea2c6ed438acb9ce28f90010101fc adds Saxon 9.7.0.21 to CI matrix.
    * [Travis](https://travis-ci.org/AirQuick/xspec/jobs/583226004)
    * The line in AppVeyor is commented out because of its slowness. We can enable it when we migrate to a faster CI.

### CODE REVIEW

**Comment by galtm** [comment]
@AirQuick : I took a quick look at the code, and I should be able to do a more substantive code review by the end of this week. If you want to merge this in, based on the review by @cirulls , I have no problem with that.

**Comment by AirQuick** [comment]
Thanks @galtm for the update. No haste for this pull request. I'll just wait for your review.

**Comment by AirQuick** [comment]
Merged the master into this branch and [added Saxon 9.7](https://github.com/xspec/xspec/pull/625/commits/784f47f76d64ca54086cadffc8337dbe105747e6) to `azure-pipelines.yml`: [Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=121)

**Comment by AirQuick** [comment]
Thanks a lot @galtm!

I'm merging this.

**Pull request merged**
