### PR TITLE
feat(schematron): compare location based on node identity

### LINKED ISSUE #984: Schematron location comparison doesn't work with SchXslt
due to URIQualifiedName introduced by schxslt/schxslt#71.

"Using another implementation of Schematron" in [Wiki](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes#using-another-implementation-of-schematron) doesn't work with SchXslt v1.4.5.

### PR DESCRIPTION
**Pull request by AirQuick**
Fixes #984

This pull request replaces `x:schematron-location-compare()` with an `is` operator and a new function `x:select-node()`. In other words, this pull request replaces the string comparison with the node identity comparison and the dynamic XPath evaluation.

This change is supposed to cover a variety of Schematron location expressions used in the _skeleton_ implementation, SchXslt and hopefully any others.

For example, on XSpec v1.x, this `x:expect-assert`

```xspec
<x:expect-assert location="/ex1:article[1]"/>
```

was compiled into this XSLT (edited for readability):

```xslt
<xsl:sequence select="exists(
  svrl:schematron-output/svrl:failed-assert
  [x:schematron-location-compare(
    '/ex1:article[1]',
    @location,
    preceding-sibling::svrl:ns-prefix-in-attribute-values)]
)"
```

With this pull request, the same `x:expect-assert` is compiled into this XSLT (edited for readability):

```xslt
<xsl:sequence select="exists(
  svrl:schematron-output/svrl:failed-assert
  [($x:context/root()/(/ex1:article[1]) treat as node())
   is
   x:select-node(
     $x:context/root(),
     @location,
     preceding-sibling::svrl:ns-prefix-in-attribute-values,
     3)]
)"
```

If the current SVRL has these entries (some parts omitted for brevity)

```xml
<svrl:ns-prefix-in-attribute-values uri="http://example.com/ns1" prefix="ex1"/>
<svrl:ns-prefix-in-attribute-values uri="http://example.com/ns2" prefix="ex2"/>
<svrl:ns-prefix-in-attribute-values uri="http://example.com/ns3" prefix="ex3"/>
<svrl:failed-assert location="/*:article[namespace-uri()='http://example.com/ns1'][1]">
```

then `x:select-node()` internally generates a stylesheet like this

```xslt
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="#all"
                version="3.0">
   <xsl:mode on-multiple-match="fail" on-no-match="fail"/>
   <xsl:template as="node()?" match="attribute() | document-node() | node()">
      <xsl:sequence xmlns:ex1="http://example.com/ns1"
                    xmlns:ex2="http://example.com/ns2"
                    xmlns:ex3="http://example.com/ns3"
                    select="/*:article[namespace-uri()='http://example.com/ns1'][1]"
                    version="3"/>
   </xsl:template>
</xsl:stylesheet>
```

and applies this stylesheet to `$x:context/root()` (`$x:context` is a variable introduced in #1089). This dynamic transformation raw result is compared with the expected node (`$x:context/root()/(/ex1:article[1])`) using the `is` operator.

### Further work
Update [Wiki](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes#using-another-implementation-of-schematron) with the latest release of [SchXslt](https://github.com/schxslt/schxslt/releases/latest).

### CODE REVIEW

**Comment by AndrewSales** [comment]
Apologies for the extra noise: just to say, I was about to propose this enhancement, using this very approach.
It will be a big win not to compare XPath location strings.

**Comment by AirQuick** [comment]
Thanks @AndrewSales for taking a look at this.
Just curious, what was your motivation to pursue this enhancement? Compatibility with the recent versions of SchXslt?

**Comment by AirQuick** [comment]
Merging this for moving on to the next step...

**Comment by AndrewSales** [comment]
Apologies, @AirQuick, I missed your reply. 
FWIW, I've been writing quite a few Schematron tests of late, but only using the "skeleton" implementation. I found having to match the paths exactly time-consuming, so the motivation was really to with productivity. Thanks for all your work!

**Comment by AirQuick** [comment]
> ### Further work
> Update [Wiki](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes#using-another-implementation-of-schematron) with the latest release of [SchXslt](https://github.com/schxslt/schxslt/releases/latest).

[Done](https://github.com/xspec/xspec/wiki/Testing-Schematron-with-Text-Nodes/_compare/5be72c2c1c317dc79f34a607e0392db7d311aeb7...0dca3fe403d726422b3b66cd7ec8af9aa0a26f52)

**Comment by AirQuick** [comment]
> I found having to match the paths exactly time-consuming, so the motivation was really to do with productivity. Thanks for all your work!

That's good to know. I didn't think about the aspect of productivity while working on this change.
Hope this feature helps.

**Comment by vincentml** [comment]
I remember @wendellpiez requested the ability to use dynamic XPath evaluation in the location comparison. It's great to see that you have been able to make it work without adding another layer of compiling XSLT!

**Pull request merged**
