### PR TITLE
Issue 182 (Enhance XSLTCoverageTraceListener)

### PR DESCRIPTION
**Pull request by cmarchand**
A proposal to solve Issue 182
I could maybe remove the @authors list in javadoc

### CODE REVIEW

**Comment by cmarchand** [comment]
Could someone give a test under Windows ?
Install Maven, then

    mvn test 

It should display a "Build success" message

**Comment by AirQuick** [comment]
I will, but after handling #188.

**Comment by AirQuick** [comment]
`mvn test` worked fine on Windows. I'm going to check the other things.

**Comment by AirQuick** [comment]
I confirmed that the coverage XML was now written to a file specified by `com.jenitennison.xsl.tests.coverage.output`. This is the first time I see the coverage XML is made well-formed.😅 Thanks for the improvement.

I committed some changes of `xspec.sh` and `xspec.bat` in your branch. They set the new system properties without trying to normalize their values at all. It is very much appreciated if any platform or environment differences are absorbed within `XSLTCoverageTraceListener`.

**Comment by AirQuick** [comment]
So,

* Can you update `XSLTCoverageTraceListener.class`, too?

* With the updated `xspec.sh` and `xspec.bat`, I've observed these values at the beginning of `enter()`, for example:

```
computedGenerateTestUtilsName=C:\Users\User\Desktop\xspec\bin\..\src\compiler\generate-tests-utils.xsl
computedIgnoreDir=C:\Users\User\Desktop\xspec\tutorial\xspec
systemId=file:/C:/Users/User/Desktop/xspec/src/compiler/generate-tests-utils.xsl
```

```
computedGenerateTestUtilsName=../src/compiler/generate-tests-utils.xsl
computedIgnoreDir=../tutorial/xspec
systemId=file:/home/user/test/xspec/test/../tutorial/xspec/escape-for-regex.xsl
```

To get them work, the following tweaks or something like them would be necessary, perhaps? (Just my quick thought, and I scarcely know Java. So please do what you think is the best.)
* `com.jenitennison.xsl.tests.coverage.generate-tests-utils`: `File(value).toURI().normalize()`
* `com.jenitennison.xsl.tests.coverage.ignore-dir`: `File(value + File.separator).toURI().normalize()`
* `systemId`: `URI(value).normalize()`

**Comment by galtm** [comment]
I'm going to close this pull request without merging it, because AirQuick closed issue #182 with a [comment](https://github.com/xspec/xspec/issues/182#issuecomment-736543078) saying the issue is obsolete. (Also, the Java code for XSLT code coverage changed significantly in XSpec 3.)

**Pull request closed without merging**
