### PR TITLE
Issue 183 (pom.xml: compile .java)

### PR DESCRIPTION
**Pull request by cmarchand**
Solved [issue 183](https://github.com/xspec/xspec/issues/183).
.java file is compiled each time a build is performed

### CODE REVIEW

**Comment by AirQuick** [comment]
@cmarchand 
@cirulls 
Is this superseded by #415?

**Comment by cirulls** [comment]
I can see some parts (like the one related to Saxon-HE) are certainly superseded but other parts (like the UTF-8 encoding) are not included in #415. @cmarchand: what do you think?

**Comment by cmarchand** [comment]
My opinion is both are required. #415 only patches this one.

**Comment by cirulls** [comment]
> My opinion is both are required.

@cmarchand: in this case would it be possible to merge the current master into this pull request and update the parts that are not yet included in the `pom.xml` file in master (like the UTF-8 encoding)? If it's easier you can also create a brand new pull request from the current master branch and close this pull request.

Is there a way to test the pom file? Something like simulating a maven build or the creation of an artifact? If so, could you share the maven command you run and the expected result? It would be great to add such test to Travis and AppVeyor so that we can make sure that any change in the pom file is not breaking anything.

**Comment by cmarchand** [comment]
Certainly not. You do not test Travis or AppVeyor. You use them.

Maven is a build system, that has its own test-suites. There is no code in a pom, only plugins that are **declared** and **configured**. Those plugins have their own test-suites, and we know they work correctly. There is no sense to test if build result is what we expect. If we want to do so, we have to create a language where we define the model of what is expected, and compare the result we get to what we expect. It's the goal of **pom**.xml, which stands for **P**roject **O**bject **M**odel.
The only test you can perform is maven ret code, which **must** be zero.

You can run `mvn install`, and check there is a `target/classes/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class`, and a `target/xspec-<version>.jar`.

But there is also support to deploy to OSSRH, and you can not test this, without deploying ; and you should not deploy until all your tests are Ok.

The only part of pom that could require tests is the config of the layout of files to include in built package. So lines [82 to 89](https://github.com/cmarchand/xspec/blob/90a7a930d6bccb9ebe0ec6719188a039db44a9e1/pom.xml#L82), and lines [129 to 140](https://github.com/cmarchand/xspec/blob/90a7a930d6bccb9ebe0ec6719188a039db44a9e1/pom.xml#L129). To do this, we could run maven (`mvn package`), and run the test suite from generated package. If test suite is successful, we know that packaging is correct.
All other parts of pom are only declarative, and there is no reason to test them.

**Comment by AirQuick** [comment]
FWIW, started from 8001c10dc9a89a9d5edbde2380b0ea628a33fd9e, `mvn install` with a certain set of parameters is running on [Travis](https://travis-ci.org/xspec/xspec/jobs/471543382#L445).

**Comment by cirulls** [comment]
> You can run mvn install, and check there is a target/classes/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.class, and a target/xspec-<version>.jar.

Yes, I was thinking something like that. And I can see this is already covered in the `mvn install` that @AirQuick mentioned (e.g. [here](https://travis-ci.org/xspec/xspec/jobs/471543382#L1145-L1146) for the generation of the jar file) so this is probably already covered. Thanks both for clarifying.

**Comment by AirQuick** [comment]
Closing, as now we have a Code Coverage test with the jar file built by Maven on Java 8/11 on Linux/Windows/macOS on every CI system of ours. (performed by `test/ci/test-maven-jar.*`)

**Pull request closed without merging**
