### PR TITLE
output expected and actual in case of failure

### PR DESCRIPTION
**Pull request by magwas**

### CODE REVIEW

**Comment by magwas** [comment]
Shall I reissue the pull request with fixed commit comment?

**Comment by magwas** [comment]
I was also thinking about making verbose failure reporting optional, but I could not figure out the canonical way. Shall I add an xslt variable declaration or should I rely on environment variable in the xslt code?

**Comment by AirQuick** [comment]
Hi, 

For this particular pull request, you don't need to reissue it. But the general guidance is available [here](https://github.com/xspec/xspec/blob/master/CONTRIBUTING.md#how-to-contribute).

Regarding the proposed changes,

* A lot of test failures like [this](https://travis-ci.org/xspec/xspec/jobs/652357248#L711)
* Needs some dedicated tests
* Needs XQuery impl

Anyway, I'm not sure if print-on-screen is viable.
The expected and the actual are already reported both in the report XML and the report HTML.
Also, the expected and the actual could be very large. (That's why they are [sometimes](https://github.com/xspec/xspec/blob/818baf546d6d2784833ada881f152cf6f4028b4e/src/compiler/generate-tests-utils.xsl#L384) written in each separated file.) Seeing large dumps on screen would be messy.

**Comment by magwas** [comment]
> For this particular pull request, you don't need to reissue it. But the general guidance is available [here](https://github.com/xspec/xspec/blob/master/CONTRIBUTING.md#how-to-contribute).

ACK

>     * A lot of test failures like [this](https://travis-ci.org/xspec/xspec/jobs/652357248#L711)

ACK
>     * Needs some dedicated tests

ACK
>     * Needs XQuery impl

ACK

> Anyway, I'm not sure if print-on-screen is viable.
> The expected and the actual are already reported both in the report XML and the report HTML.
> Also, the expected and the actual could be very large. (That's why they are [sometimes](https://github.com/xspec/xspec/blob/818baf546d6d2784833ada881f152cf6f4028b4e/src/compiler/generate-tests-utils.xsl#L384) written in each separated file.) Seeing large dumps on screen would be messy.

I understand that for some users it does not give an advantage. This is why I am asking how to make it optional.
However for me - and I am sure that for other developers too - the ability to see the details of the failure without the need for additional steps makes the red-green-refactor cycle much faster.

**Comment by AirQuick** [comment]
Because user demands vary and also XSLT and XQuery have different limitations, a better approach would be overriding `src/reporter/format-xspec-report.xsl` and doing whatever you want in your overriding stylesheet.

This is not explicitly documented but already possible in Ant (via `xspec.html.reporter.xsl` Ant property). For example, `ant -lib "saxon9he.jar" -Dxspec.xml=tutorial/escape-for-regex.xspec -Dxspec.html.reporter.xsl=src/reporter/format-xspec-report-folding.xsl` generates a different HTML report than the default `format-xspec-report.xsl`. (`format-xspec-report-folding.xsl` imports `format-xspec-report.xsl` and does some customization. Likewise you may be able to invoke `xsl:message` in your importing stylesheet.)

Currently CLI (`bin/xspec.*`) does not provide such facility, but it's easy to add it.

**Comment by AirQuick** [comment]
> Because user demands vary and also XSLT and XQuery have different limitations, a better approach would be overriding `src/reporter/format-xspec-report.xsl` and doing whatever you want in your overriding stylesheet.
> ...
> Currently CLI (`bin/xspec.*`) does not provide such facility, but it's easy to add it.

I opened #818 for it. Its test demonstrates my suggestion:

```console
$ export HTML_REPORTER_XSL=test/format-xspec-report-messaging.xsl 
$ bin/xspec.sh tutorial/escape-for-regex.xspec 
...
Formatting Report...
passed: 5 / pending: 0 / failed: 1 / total: 6
=== When processing a list of phrases Strings should be escaped and status attributes should be added ===
--- Actual Result ---
XPath /element() from:
<phrases xmlns:functx="http://www.functx.com">
   <phrase status="changed">Hello!</phrase>
   <phrase status="changed">Goodbye!</phrase>
   <phrase status="same">\(So long!\)</phrase>
</phrases>
--- Expected Result ---
XPath /element() from:
<phrases xmlns:functx="http://www.functx.com">
   <phrase status="same">Hello!</phrase>
   <phrase status="same">Goodbye!</phrase>
   <phrase status="changed">\(So long!\)</phrase>
</phrases>
Report available at tutorial/xspec/escape-for-regex-result.html
Done.
```

**Comment by AirQuick** [comment]
Closing, as [`v1.6.0`](https://github.com/xspec/xspec/releases/tag/v1.6.0) has been released with #818.

**Pull request closed without merging**
