### PR TITLE
Fix issue 412 (select with href or child node always sorts nodes and eliminates duplicates)

### LINKED ISSUE #412: select with href or child node always sorts nodes and eliminates duplicates
**test.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<p>
	<e1 />
	<e2 />
</p>
```

**test.xsl** (does nothing)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" />
```

**test.xspec**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description stylesheet="test.xsl" xmlns:x="http://www.jenitennison.com/xslt/xspec">
	<x:scenario label="Selecting (e2, e1, e1) from a document containing e1 followed by e2">
		<x:call function="one-or-more">
			<x:param href="test.xml" select="//e2, //e1, //e1" />
		</x:call>
		<x:expect label="should produce (e2, e1, e1)">
			<e2 />
			<e1 />
			<e1 />
		</x:expect>
	</x:scenario>
</x:description>
```

This `x:expect` returns Failure. The result is
```xml
<e1 /><e2 />
```
which means that the nodes are sorted in document order and the duplicates are eliminated as if `select="//e2, //e1, //e1"` were `select="//e2 | //e1 | //e1"` or some such.

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #411. So needs to be handled after that.

---

Fixes #412 for XSLT. (Unfortunately I don't know how to fix it for XQuery.)

The problem is that `mode="test:generate-variable-declarations"` template generates variable declarations using [`/` operator](http://www.w3.org/TR/xpath-31/#id-path-operator) like this:

```xml
<xsl:variable name="d29e1" select="$d29e1-doc/(//e2, //e1, //e1)"/>
```

With this pull request, the variable is declared like this

```xml
<xsl:variable name="d29e1" as="item()*">
   <xsl:for-each select="$d29e1-doc">
      <xsl:sequence select="//e2, //e1, //e1"/>
   </xsl:for-each>
</xsl:variable>
```

without using `/`.

### Commits
* b7bed17b68a1e8e1b7c3bbfb1b70b8bcb6a12cf8 reproduces the problem ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/447845111#L1563-L1571), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/19882766/job/lx4ol8lf7lsg5ahd#L581))
* f1cfe09a9e68c1d1d386057debf1dcac8a53471d fixes XSLT
* 92db219e4ae0a1202a9e18b28e11fab95d57bc4b simplifies an expression in one of the tests. The expression had to be weird, before fixing this problem.

### CODE REVIEW

**Comment by AirQuick** [comment]
@cirulls 
Merged this bug fix.

@galtm 
#475 has a small conflict with this change in `generate-tests-helper.xsl`. I think it's easy to resolve.
As written in [the initial comment](https://github.com/xspec/xspec/pull/413#issue-226626352) here, the goal of the change is replacing this pattern of variable declaration
```xml
<xsl:variable name="d29e1" select="$d29e1-doc/(//e2, //e1, //e1)"/>
```
with this pattern
```xml
<xsl:variable name="d29e1" as="item()*">
   <xsl:for-each select="$d29e1-doc">
      <xsl:sequence select="//e2, //e1, //e1"/>
   </xsl:for-each>
</xsl:variable>
```

**Comment by galtm** [comment]
> #475 has a small conflict

@AirQuick 
OK, I will take a look in the next few days.

**Comment by galtm** [comment]
> #475 has a small conflict with this change in `generate-tests-helper.xsl`.

@AirQuick 
I pushed commit 09219e7c6a264a52dc850e9056d05c9c7d346424 to PR #475. It should be basically a reinsertion of my change into the latest master revision of the file. I had to insert part of my code in a different spot to adapt to your changes.

**Comment by AirQuick** [comment]
@galtm 
I should have mentioned that `xsl:element` had been consolidated and thus you would need a tweak after reinsertion. 😎

**Comment by galtm** [comment]
> `xsl:element` had been consolidated

I should have noticed in any case. I uploaded to #475 a better adaptation to your changes: 428a7116e8a7072f377bd9cd01dacfdb2736426d.

**Pull request merged**
