### PR TITLE
Balisage improvements to Schematron support

### PR DESCRIPTION
**Pull request by vincentml**
Pull request for issue #140. 

Improvements to Schematron support:

* Added new element `<x:expect-rule>` to test that a rule is fired/thrown.
* Added new attribute `@count` to test that an assert, report, or rule is thrown a specific number of times.
* Changed the RelaxNG grammar to allow `<x:expect>` in scenarios that have Schematron-specific expect elements.
* Changed the location of the compiled Schematron XSLT to the same folder as the Schematron so that relative file paths that are used within the Schematron will work. 
* Extended the `@id` attribute matching to include the `@id` attribute on the Schematron pattern element.

### CODE REVIEW

**Comment by vincentml** [comment]
@cirulls and @AirQuick do you have any insights as to why [one test run](https://travis-ci.org/xspec/xspec/jobs/297769210) failed? 

Might this have something to do with the "Picked up _JAVA_OPTIONS" message in Travis?

I tested the merge locally and all tests pass when I run the test scripts locally under Windows 7 and Ubuntu.

**Comment by AirQuick** [comment]
@vincentml , It's probably because #148 are not yet merged to the PR branch.

FWIW, AppVeyor tests are not affected by `JAVA_TOOL_OPTIONS`, because of this: https://github.com/xspec/xspec/blob/40316746f67e9382f434e446cd4f1a12c210c938/test/xspec-bat.cmd#L534-L539

**Comment by cirulls** [comment]
Yes, as @AirQuick suggested, you integrate #148 in your branch the test will probably pass. Note that this was a change introduced in Travis in September 2017 (see #148 for details), I noticed it last time I merged code into `master`.

**Comment by vincentml** [comment]
Thanks @AirQuick and @cirulls ! All tests are passing now after merging commit 5f2cf8c6e3dea703ef08fd9d6ccaab0b37dff947 into the branch.

**Pull request merged**
