### PR TITLE
Schema: Move node-selection's href and any-content into choice

### PR DESCRIPTION
**Pull request by AirQuick**
In the current schema, [`node-selection`](https://github.com/xspec/xspec/blob/63cf95d7eade5678e5c994fae18ff69d3410ac5d/src/schemas/xspec.rnc#L190-L195) makes both `href` and content optional. So it allows these elements:
```xml
<x:context href="uri">content</x:context>
```
```xml
<x:param href="uri" name="foo">content</x:param>
```
```xml
<x:expect href="uri" label="foo">content</x:expect>
```
which don't make sense.
As for `x:context`, the scenario is terminated: https://github.com/xspec/xspec/blob/63cf95d7eade5678e5c994fae18ff69d3410ac5d/src/compiler/generate-xspec-tests.xsl#L123-L130
As for `x:param` and `x:expect`, content is ignored: https://github.com/xspec/xspec/blob/63cf95d7eade5678e5c994fae18ff69d3410ac5d/src/compiler/generate-tests-helper.xsl#L51-L66

This PR updates the schema to reflect it. The elements above are no longer allowed by the updated schema.

Also added are 
* Simple tests to validate the tests/tutorial against the schema (c07917e73f914992f3b71240cc14e807834f47b7)
* Tests to verify that the implementation does select `href` over `any-content` (38a77b0244ffdd0a2c7c907e5793c19f0c23b8cb)
* Tests to verify that the schema does detect violation (288854935012d1acc57505cfa8bd6eac74fb1866)

### CODE REVIEW

**Comment by vincentml** [comment]
@AirQuick This schema change is a good usability improvement, and the tests that you have already added will be very helpful when new tests are added and when changes are made to the schema.

`test/end-to-end/cases/*.xspec` could possibly be added to these tests, however `xspec-rule.xspec` fails validation to the schema due to the `variable` and `apply` elements.

**Comment by AirQuick** [comment]
Thanks, @vincentml 
Right. `variable` and `apply` should be addressed some day: #60

**Comment by AirQuick** [comment]
The two scenarios in `test/end-to-end/cases/xspec-rule.xspec` are disabled by `pending` attributes. And in this case, the `pending` attributes are not being tested. (On the other hand, `pending` attributes in `xspec-pending.xspec` *are* actually tested.)
So, we can comment out those two scenarios safely. I commented out them in eb6eed6.
Now we can include `test/end-to-end/cases/*.xspec` in validation testing. I did so in df8513e .

**Comment by AirQuick** [comment]
obsoleted by #307

**Pull request closed without merging**
