### PR TITLE
feat(schematron): support /x:description/attribute(run-as)

### LINKED ISSUE #1287: Support run-as=external on Schematron
Currently `src/schematron/schut-to-xspec.xsl` discards `/x:description/@run-as`.

However, https://groups.google.com/g/xspec-users/c/dNvDGZfKVz0/m/-FzoJ1K_AQAJ suggests that there seems to be a use case where `@run-as=external` may help on Schematron when the Schematron schema relies on the global context item.

After implementing this, don't forget to add a use case to [Wiki](https://github.com/xspec/xspec/wiki/External-Transformation#use-cases).

### PR DESCRIPTION
**Pull request by AirQuick**
Closes #1287 

With `/x:description/@run-as='external'`, each Schematron scenario will have its own global context item which is `root() treat as document-node()`. (More specifically, it just follows the [_apply-templates_ invocation rule](https://github.com/xspec/xspec/wiki/External-Transformation#apply-templates-invocation-xcontext-without-xcalltemplate).)

#### Further work
Add a use case to [Wiki](https://github.com/xspec/xspec/wiki/External-Transformation#use-cases).

### CODE REVIEW

**Comment by ohsh6o** [comment]
I would love to eventually test this @AirQuick, is there a prudent way to also pass in other `<x:param>` parameters and not just the global context? Or have I misunderstood the wiki and that works out of the box?

**Comment by AirQuick** [comment]
@ohsh6o 
I forked your example you had posted on the google groups, and I adapted it to this pull request.

https://github.com/AirQuick/fedramp-automation/commits/xspec-2825e7b

It seems to work:

```console
$ git clone https://github.com/AirQuick/fedramp-automation.git -b xspec-2825e7b
Cloning into 'fedramp-automation'...
...
$ git clone https://github.com/xspec/xspec.git
Cloning into 'xspec'...
...
$ cd xspec
$ git fetch origin pull/1294/head:pull_1294
...
 * [new ref]         refs/pull/1294/head -> pull_1294
$ git checkout pull_1294
Switched to branch 'pull_1294'
$ mkdir -p /tmp/saxon
$ # Use Saxon 10.3. Saxon 10.0, 10.1 and 10.2 have critical bugs in terms of XSpec v2.0 and Schematron.
$ export SAXON_CP=/tmp/saxon/Saxon-HE-10.3.jar
$ wget -O "${SAXON_CP}" https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.3/Saxon-HE-10.3.jar
...
$ bin/xspec.sh -s ../fedramp-automation/resources/validations/test/ssp.xspec
...
Running Tests...
Testing with SAXON HE 10.3
For an OSCAL FedRAMP SSP
..when the security sensitivity level
..is not defined at all
it is invalid. assert no-security-sensitivity-level
      FAILED
..is set to a value from the official FedRAMP list
it is valid. not assert invalid-security-sensitivity-level
..is not set to a value from the official FedRAMP list
it is invalid. assert invalid-security-sensitivity-level
..when control implementations are defined
..and requirements are implemented
..a count of all total controls
must be reported. report all-requirements-report
..a count of all controls with a status of planned
must be reported. report planned-requirements-report
..a count of all controls with a status of partial
must be reported. report partial-requirements-report
..and each one has its implementation status set
it is valid. not assert invalid-implemented-requirements-count
..and the total number of requirements is zero
it is invalid. assert invalid-implemented-requirements-count
..and all required implementations are not yet complete
it is invalid. assert incomplete-implementation-requirements
      FAILED

Formatting Report...
passed: 7 / pending: 0 / failed: 2 / total: 9
Report available at ../fedramp-automation/resources/validations/test/xspec/ssp-result.html
Done.
```

Basically, with `run-as=external`, every `x:scenario` will turn its `x:context` into its global context item when running the compiled Schematron schema.

> is there a prudent way to also pass in other `<x:param>` parameters and not just the global context?

If you mean to supply different `xsl:param` values in each `x:scenario`, it is not possible. At the moment, `xsl:param` can be supplied only by `/x:description/x:param` which is global.
We have a plan to make `x:param` scenario-local (#991), but have not worked on it yet.

**Comment by ohsh6o** [comment]
@AirQuick, this is very cool, I will evaluate a little bit later in the week. I am a little new to this, but this and #991 would be amazing for me to go back to generalized global parameters. Maybe I can find some way to pick this up and help? I am a little new to XSLT, but let me know!

**Comment by AirQuick** [comment]
This change won't affect existing tests. I'm merging it.

> #### Further work
> Add a use case to [Wiki](https://github.com/xspec/xspec/wiki/External-Transformation#use-cases).

Done. Since turning `x:context` into the global context seems to be a general popular demand, I've raised it in the use case list in Wiki and removed particular examples.

**Pull request merged**
