### PR TITLE
ci(deps): bump Saxon from 10.6 to 10.8

### PR DESCRIPTION
**Pull request by galtm**
This pull request updates the Saxon 10 version used for testing.

The minor update in `test/xsl-result-document.xspec` that #1543 made for Saxon 10.6 needed further modification for Saxon 10.8 (e88dc5d2f70e5a8511ca0e54f2ce6fa991cbee4b).

Also, Saxon 10.8 and 10.6 have different handling of `/` when there is no context item, so I added a workaround in `src/schematron/step3.xsl` (04d806b43682c1ddff21fce5e80f38840d2b77bd).

### CODE REVIEW

**Comment by AirQuick** [comment]
Thanks for spotting the slight change in 10.8. And sorry for being too late. Here's my afterthoughts.

Like https://github.com/xspec/xspec/issues/1618#issuecomment-1257185678, I don't think this `step3.xsl` should be a place for generic patches for the *skeleton* implementation. (`x:enable-schematron-text-location` was a special case. It fires only when a private parameter is set and the parameter is set only when absolutely necessary.)
To clarify that, I'd propose moving `stpe3.xsl` from `src/` to `test/`. I'll open a pull request for that, after resolving my personal blocking issues:
- My workstation crashed recently and not booting. I have to rebuild it.
- Regain my Saxon license, though I'm not happy with its new subscription model...

**Comment by galtm** [comment]
@AirQuick , thanks for your suggestion about a better way to handle issues with the skeleton implementation. I look forward to your pull request when it's ready, and good luck with the blocking issues!

**Comment by galtm** [comment]
Welcome back, @AirQuick !

**Comment by AirQuick** [comment]
I'll open a pull request after merging #1713.

**Comment by AirQuick** [comment]
> Also, Saxon 10.8 and 10.6 have different handling of `/` when there is no context item, so I added a workaround in `src/schematron/step3.xsl` ([04d806b](https://github.com/xspec/xspec/commit/04d806b43682c1ddff21fce5e80f38840d2b77bd)).

`XPDY0002` in this case was implemented probably by https://saxonica.plan.io/issues/5131 on Saxon 10.7.

**Comment by galtm** [comment]
> I'll open a pull request after merging #1713.

OK, sounds good. While you're doing that, is it worthwhile to see if bumping Saxon from 10.8 to 10.9 is straightforward, or leave that for a separate pull request?

**Comment by AirQuick** [comment]
Creating a separate pull request would be nice. From my past experience, each Saxon release has some subtle pitfall. Recording the successful execution of XSpec test set on a particular Saxon release would aid in narrowing down problems.

**Comment by galtm** [comment]
OK. By the way, I've been working toward making XSpec run with Saxon 11.5. There are indeed some pitfalls, but I am making progress. Look for a separate issue about that, hopefully next week.

**Comment by galtm** [comment]
> bumping Saxon from 10.8 to 10.9

FYI, the separate pull request for Saxon 10.9 is #1718

**Pull request merged**
