### PR TITLE
Fix issue 453 (XSLT ns prefix is changed) 538 (x:context/x:param curly bracket) and test issue 29 (AVT in user content)

### LINKED ISSUE #29: escaping XPath expressions in attributes
Such a scenario generates non-compilable XSL code :
```
<x:context>
  <file>
    <element path="/Q{http://www.w3.org/1999/XSL/Transform}stylesheet[1]/Q{http://www.w3.org/1999/XSL/Transform}template[1]">
    </element>
  </file>
</x:context>
```
Because  of the curly brackets in the attribute value, when copied inside a <xsl:* /> element, XSL compiler tries to execute the XPath expression.

If in the context, I double the curly braces, then it works correctly. But is it xspec writer responsability to escape the curly braces, or it is xspec compiler responsability ?

### LINKED ISSUE #453: XSpec forcibly changes XSLT namespace prefix
```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description query="x-urn:test:do-nothing" query-at="do-nothing.xquery"
	stylesheet="do-nothing.xsl" xmlns:do-nothing="x-urn:test:do-nothing"
	xmlns:x="http://www.jenitennison.com/xslt/xspec"
	xmlns:xslt="http://www.w3.org/1999/XSL/Transform">

	<x:scenario label="XSLT namespace">
		<x:call function="exactly-one">
			<x:param as="element(xslt:element)">
				<xslt:element />
			</x:param>
		</x:call>
		<x:expect label="name()" select="'xslt:element'" test="name($x:result)" />
	</x:scenario>

</x:description>
```

This `x:expect` returns Failure (incorrect) on XSLT.
XQuery returns Success (correct).

### LINKED ISSUE #538: Compiled test is invalid if select attribute of x:context/x:param uses syntax like map{'key': 'myvalue'}
If a scenario uses syntax like
```
    <x:context>
      <myelement/>
      <x:param name="myparam" select="map{'key': 'myvalue'}"/>
    </x:context>
```
then the compiled test is invalid. See sample code, below. The log includes these error messages:

```
run-xslt-test:
     [echo] Running XSLT Tests...
     [java] Syntax error at char 9 in {map{'key': 'myvalue'} in expression in x:param/@select on line 46 column 69 of map_param.xsl:
     [java]   XPST0003: Unexpected token ":" beyond end of expression
     [java] Syntax error at char 9 in {map{'key': 'myvalue'} in expression in x:param/@select on line 63 column 69 of map_param.xsl:
     [java]   XPST0003: Unexpected token ":" beyond end of expression
     [java] Errors were reported during stylesheet compilation
```

From a quick look, I think the bug may be related to the `<xsl:template match="x:context | x:param" mode="x:report">` template in `compiler/generate-xspec-tests.xsl`. I suspect that the `<xsl:template match="@select" mode="x:report">` template does not get reached for `x:param` inside `x:context`.

**To reproduce problem:**

XSpec code

```xml
<?xml version="1.0" encoding="UTF-8"?>
<x:description
  xmlns:x="http://www.jenitennison.com/xslt/xspec"
  xmlns:map="http://www.w3.org/2005/xpath-functions/map"
  xslt-version="3.0"
  stylesheet="map_param.xsl">

  <!-- Build failure if parameter passed to template rule uses map{'key': 'value'} syntax in @select -->

  <!-- The commented-out scenarios below are a problem. The uncommented scenarios
    represent a potential workaround followed by a similar usage that is not
    a problem. -->
  <!-- ======================================================================= -->

  <!-- The following scenarios have a build error in Oxygen, even if marked as pending.
  <x:scenario label="Testing a moded template with a map parameter" pending="error">
    <x:context mode="mymode">
      <myelement/>
      <x:param name="myparam" select="map{'key': 'myvalue'}"/>
    </x:context>
    <x:expect label="has a build error if map parameter uses map{} syntax">myvalue</x:expect>
  </x:scenario>

  <x:scenario label="Testing a template rule with a map parameter" pending="error">
    <x:context>
      <myelement/>
      <x:param name="myparam" select="map{'key': 'myvalue'}"/>
    </x:context>
    <x:expect label="has a build error if map parameter uses map{} syntax">myvalue</x:expect>
  </x:scenario>
  -->

  <x:scenario label="Testing a moded template with a map parameter">
    <x:context mode="mymode">
      <myelement/>
      <x:param name="myparam" select="map:merge((
        map:entry('key1','myvalue1'),
        map:entry('key2','myvalue2'),
        map:entry('key','myvalue')
        ))"/>
    </x:context>
    <x:expect label="succeeds if map parameter uses map:merge">myvalue</x:expect>
  </x:scenario>
  <x:scenario label="Testing a template rule with a map parameter">
    <x:context>
      <myelement/>
      <x:param name="myparam" select="map:merge((
        map:entry('key1','myvalue1'),
        map:entry('key2','myvalue2'),
        map:entry('key','myvalue')
        ))"/>
    </x:context>
    <x:expect label="succeeds if map parameter uses map:merge">myvalue</x:expect>
  </x:scenario>
  <x:scenario label="Testing a named template with a map parameter">
    <x:call template="mytemplate">
      <x:param name="myparam" select="map{'key': 'myvalue'}"/>
    </x:call>
    <x:expect label="succeeds">myvalue</x:expect>
  </x:scenario>

  <!-- In the XSLT file that results from compiling this XSpec file, the
    parameter of the named template appears as
    <x:param name="myparam" select="map{{'key': 'myvalue'}}"/>
    while the parameter of the moded template appears as
    <x:param name="myparam" select="map{'key': 'myvalue'}"/>
    without doubling the curly braces.
    -->
</x:description>
```

XSLT code

```xslt
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:x="http://www.jenitennison.com/xslt/xspec"
  exclude-result-prefixes="xs"
  version="3.0">
  
  <xsl:template match="myelement" mode="mymode">
    <xsl:param name="myparam" as="map(*)"/>
    <!--<foo name="x" select="map{'a': 'b'}"/>-->
    <!-- If uncommented, the line above has a validation error (Saxon-PE 9.8.0.8). -->
    <xsl:value-of select="$myparam('key')"/>
  </xsl:template>

  <xsl:template match="myelement">
    <xsl:param name="myparam" as="map(*)"/>
    <xsl:value-of select="$myparam('key')"/>
  </xsl:template>

  <xsl:template name="mytemplate">
    <xsl:param name="myparam" as="map(*)"/>
    <xsl:value-of select="$myparam('key')"/>
  </xsl:template>

</xsl:stylesheet>
```

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #444. So needs to be handled after that.

---

Closes #29
Fixes #453 
Fixes #538

The root cause of #453 is that `test:create-node-generator` creates a node when it must create a node *generator*. This pull request fixes it.
As a bonus, #538 is fixed together.

* c46ad5b695fb6d08e4dba89eb55d43ef91768946 reproduces #453 ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/457902232#L1330-L1335), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/20458440/job/qge580n9qmgpr5er#L611))
* 459b13332e04ceb7886c4936b19eb2b7adea1c96 fixes #453 and #538 (but this fix disables [AVT](https://github.com/xspec/xspec/issues/29#issuecomment-449447690))
* ~~3396ae02ba7a5958de26177d02f790c3c9a36bf3 tests #29 which gets fixed together~~
* 9d8bdce8df47783e35d8238a52b99c1f124bbce4 tests AVT
* e92f4441e33b1b0872b111cfef67d2d83a95ef48 reinstates AVT
* 7bbeb06052950897eb1b414c93a35ba5b979233c tests #538 which [failed](https://travis-ci.org/xspec/xspec/jobs/502077027#L1458-L1467) on #444

### CODE REVIEW

**Comment by AirQuick** [comment]
@cirulls
Merged this bug fix (for #453 and #538) with a new test (for #29).

@galtm 
Can you merge the master into #475 and consider adding `x:variable` cases to `test/xspec-avt.xspec`?
The goal of `test/xspec-avt.xspec` is to ensure that attributes in user content (including `x:variable//*/@*`) work as described in [Wiki](https://github.com/xspec/xspec/wiki/Writing-Scenarios#attributes-in-content).

**Comment by galtm** [comment]
@AirQuick 
Yes, I will. It will probably be early next week, though, because this week will be very busy for me.

**Comment by AirQuick** [comment]
@galtm 
Fortunately, after finishing consuming [the pull requests for v1.3.0](https://github.com/xspec/xspec/milestone/5), I'm going to stop merging the other pull requests for maybe two weeks. So you won't be pressed hard :)

**Comment by galtm** [comment]
@AirQuick 
Hope you enjoy your break after all your work for v1.3.0. :)
I uploaded https://github.com/xspec/xspec/pull/475/commits/d9840e07d10e5158154a2a76a34a7d6715a1da4c to #475  with some AVT tests for XSpec variables.

**Comment by galtm** [comment]
@AirQuick  and @cirulls ,
I'm not sure where to ask the following general question: Are there certain code reviews in this project that would be useful for me to do, in the interest of (a) getting pull requests integrated more quickly, and/or (b) providing an extra set of eyes where needed, and/or (c) increasing my familiarity with this code base so that whatever contributions I make will be better? You've been tackling a backlog of pull requests and I don't want to interfere with that. But I'm looking for your input on what would be helpful. It's semiannual "planning season" for me, and I would consider your input along with the other tasks I expect to work on in the next several months.

On a more specific note, I think I would need a little help understanding what to make of pull requests that have large numbers of files in them. Are there sometimes only a few files that specifically address a bug or enhancement, and all the other files in the PR are coming from some other PR on the same branch? Is doing code reviews in the right sequence the best way to identify the relevant subset of files? Thanks for any insight.

**Comment by cirulls** [comment]
@galtm: First of all, thanks for your contributions, I look forward to seeing your work on `x:variable` on `master`!

Here are my answers to your  questions:

> I'm not sure where to ask the following general question

It's fine to ask it here but you can also start an internal discussion within the development team [here](https://github.com/orgs/xspec/teams/xspec/discussions). You should have received an invite to join. 

>About reviewing pull requests

It would be great if you could review pull requests, this is a very useful thing for XSpec and, as you said, it will help you familiarize with the code base. I'd suggest to coordinate with @AirQuick for this since he raised most of the outstanding pull requests. @AirQuick: would that be fine for you?

> I think I would need a little help understanding what to make of pull requests that have large numbers of files in them

I think most (if not all) of @AirQuick's pull requests are usually fairly small and change one thing at the time, he's really good with that and this helps the reviewing and merging process. However, you have to take them sequentially as he's very prolific! I'm mainly responsible for the current backlog of pull requests as I couldn't keep up with his sterling work, that's why at the beginning of this year we decided to merge his pull requests without necessarily having a review (unless @AirQuick explicitly asks for one). However, if you could help with the review process it will benefit everybody. You could start by looking at the pull requests scheduled for the next XSpec release in the [To do column](https://github.com/xspec/xspec/projects/5).     

> Is doing code reviews in the right sequence the best way to identify the relevant subset of files?

For now, I think so. Once the current backlog of pull requests drops to an acceptable level for @AirQuick, it may be better to initiate pull requests directly from the latest `master`. @AirQuick: what do you think about this? Do you think this is going to be feasible at some point?

**Comment by galtm** [comment]
@cirulls , thanks for inviting me to the development team! :) I started a discussion thread there to avoid overburdening this pull request page.

**Pull request merged**
