### PR TITLE
Fix command line Schematron to resolve URI with catalog

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #324. So needs to be handled after that.

---

XSpec CLI fails to resolve Schematron URI with catalog.

The root cause of the problem is that URI is resolved as [string manipulation](https://github.com/xspec/xspec/blob/4b90f666da8d6db1f52ee0092a9c1f933bb7d2fa/bin/xspec.sh#L316-L317).
This pull request fixes it by throwing URI to [catalog](https://github.com/xspec/xspec/commit/2b5ebaca5e506f78d78e53566f4252bc788cdb72#diff-339b9f09441f30a5b6ac2f34577cf3f7R19).

* 4d39175964e21ecb3e026a882648691feb5e465a reproduces the problem. ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/423690254#L1463-L1474), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/build/1182-fix_sch-catalog/job/3jn8kcx6tv8wljqt#L344))
* 2b5ebaca5e506f78d78e53566f4252bc788cdb72 fixes the problem.

### CODE REVIEW

**Comment by AirQuick** [comment]
Although this pull request contains a lot of commits for historical reasons, all that needs to be reviewed in the end is a pair of commits mentioned in the initial comment:
> * 4d39175964e21ecb3e026a882648691feb5e465a reproduces the problem. ([Travis](https://travis-ci.org/AirQuick/xspec/jobs/423690254#L1463-L1474), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/build/1182-fix_sch-catalog/job/3jn8kcx6tv8wljqt#L344))
> * 2b5ebaca5e506f78d78e53566f4252bc788cdb72 fixes the problem.

**Comment by AirQuick** [comment]
@cmarchand, @dmj
Just like https://github.com/xspec/xspec/pull/322#issuecomment-457917899, this pull request renames the `stylesheet` param in `schut-to-xspec.xsl` as follows:
https://github.com/xspec/xspec/blob/2b5ebaca5e506f78d78e53566f4252bc788cdb72/src/schematron/schut-to-xspec.xsl#L8
This renaming intends to clarify the parameters' nature.
Again I guess this change has little impact on you, but just wanted to let you know beforehand.

**Comment by cmarchand** [comment]
Noted on my side, with a FIXME comment and a link to this issue. Expected target release is 1.2 ?
Best regards

**Comment by AirQuick** [comment]
Not scheduled to be included in the upcoming v1.2.0.
Will be merged into master soon after releasing v1.2.0, provided that no concern arises.

**Comment by AirQuick** [comment]
@cirulls 
Merged this bug fix.

**Pull request merged**
