### PR TITLE
Noting CSS difference between actual and expected

### PR DESCRIPTION
**Pull request by galtm**
This wiki change is to answer a question I had the first time I reviewed some files in the test/end-to-end area.

### CODE REVIEW

**Comment by AirQuick** [comment]
[Wiki update](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/a076c0a%5E...a076c0a) also looks good to me. Thanks for sharing the tips.

> If you earlier ran tests manually..., then remove the inner `xspec` folder

This behavior annoys me, too. We may want to have the test script handle the temp folder more gracefully.

**Comment by AirQuick** [comment]
@cirulls 
Merged this test documentation update.

**Comment by galtm** [comment]
> [Wiki update](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/a076c0a%5E...a076c0a) also looks good to me. Thanks for sharing the tips.

No problem. Thanks for reviewing them. More graceful handling of the temp folder would be nice, subject to time/priority constraints.

**Comment by cirulls** [comment]
> This behavior annoys me, too. We may want to have the test script handle the temp folder more gracefully.

This occurred to me too. +1 for graceful handling of the temp folder.

**Pull request merged**
