### PR TITLE
Restore test file format

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #317. So needs to be handled after that.

---

`.xspec` files in the repository have experienced unrelated format modifications in these few years.
So it's hard to see what the actual changes are.

This pull request restores [the original format](https://github.com/xspec/xspec/tree/5105319fd60765730b744a3099b53ddd99ace617) of these files:

* `test/generate-tests-utils.xspec`
* `test/generate-x-utils.xspec`
* `test/generate-xspec-tests.xspec`
* `test/unit-expect-xsl.xspec`
* `test/xspec-focus-2.xspec`
* `test/xspec-rule.xspec`
* `test/xspec-variable.xspec`
* `test/end-to-end/cases/xspec-focus-1.xspec`
* `test/end-to-end/cases/xspec-function.xspec`
* `test/end-to-end/cases/xspec-import.xspec`
* `test/end-to-end/cases/xspec-imported.xspec`
* `test/end-to-end/cases/xspec-pending.xspec`
* `tutorial/escape-for-regex.xspec`

Now you can clearly see what has actually changed in those files.

### CODE REVIEW

**Comment by AirQuick** [comment]
The latest automated tests were not submitted successfully. (Maybe I pushed the last commit too quickly.)
They are successful on my repository: [Travis](https://travis-ci.org/AirQuick/xspec/builds/483835809), [AppVeyor](https://ci.appveyor.com/project/AirQuick/xspec/builds/21856074)

**Comment by cirulls** [comment]
@AirQuick: I tried to trace the failed build in AppVeyor or to trigger manually the webhook in GitHub but without success. I wonder if you could push a dummy commit to the branch of this pull request to re-trigger the test build on AppVeyor, this should turn the checks into green. Since we are always doing squash and merge into master the dummy commit should not add junk in your branch. 

If you have a better idea to turn the AppVeyor check into green, feel free to share it.

**Comment by AirQuick** [comment]
Thanks @cirulls , your idea has made this pr green again.

**Comment by AirQuick** [comment]
@cirulls 
Now merged.

@galtm 
#475 now conflicts with the master.
As described in [the initial comment](https://github.com/xspec/xspec/pull/318#issue-212327690), this change pertains only to *format*. Nothing in `xspec-variable.xspec` has been changed in essence.
Hope you can resolve the conflict easily honoring the restored format.

**Comment by galtm** [comment]
I should have some time today and/or over the weekend to catch up on your recent comments.

**Comment by cirulls** [comment]
@AirQuick: thanks, I added this to the release notes.

I think I am party responsible of weird formatting on some files. Just out of interest and for future commits: do you use the automatic format and indent in oXygen to format files before committing them? Or do you have any rules for formatting files (e.g. tabs, number of spaces, etc.)?

**Comment by AirQuick** [comment]
Formatting wasn't weird and I think it's fine to change it occasionally (inserting some spaces, wrapping too long grew lines).
The problem was that formatting changes were intermingled with actual changes, which made it difficult to see the actual history from 5105319fd60765730b744a3099b53ddd99ace617. I was so puzzled that I had to restore the original format before proposing further changes.

I usually use the automatic formatting on oXygen and do so when I make *initial* commits (because this repository hasn't established any rule yet) or modify a file which was first created by me (because I know its initial automatic formatting rule) or refactor a file broadly (because the changes are disruptive anyway).
When I just modify an existing file which was first submitted by other people, I refrain from the automatic formatting because doing so makes it difficult to track actual changes.

At some point in future we may want to
1. establish our formatting rule based on oXygen's automatic formatting [options](https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/format-and-indent-xml-x-modes2.html#format-and-indent-xml__how_formats_and_indents_xml) (just because oXygen appears to be the most popular)
1. create an oXygen project file (`xspec.xpr`?) and put it in the repository root (and [beautify it](https://www.oxygenxml.com/pipermail/oxygen-user/2018-April/006125.html)? - I have no experience with it)
1. set the [project level options](https://www.oxygenxml.com/doc/versions/20.1/ug-editor/topics/preferences-storing.html) to realize the automatic formatting rule
1. enforce the automatic formatting on new files submitted to this repository
1. apply the automatic formatting to some of the existing files when they are considered very stable

**Comment by cirulls** [comment]
This sounds like a good plan although it may take some time to implement it and enforce it via the CI systems. I created #515 to record this conversation in an issue.

**Pull request merged**
