### PR TITLE
refactor: split src/compiler/generate-*-utils.*

### PR DESCRIPTION
**Pull request by AirQuick**
As the first step of #948, this pull request splits `src/compiler/generate-*-utils.*` into several modules in `src/common/`.

#### Rationale

- `generate-*-utils.*` files are not used by the compilers. They are used by the compiled stylesheet/query and the reporters. `src/compiler/` isn't a right place for them.
- `generate-*-utils.*` consist of several groups of functions/templates. Putting them together in a single file makes it hard to understand each scope.

#### Result

- The utils are split into 5 modules in `src/common/`:
  - `deep-equal.*` (`deq:` prefix)
  - `report-sequence.*` (`rep:` prefix)
  - `saxon-config.xsl`
  - `wrap.xsl`
  - `xml-report-serialization-parameters.*`
- I didn't want to introduce new prefixes (`deq` and `rep`), but XQuery requires them.
- `test:` prefix is replaced with `x:` wherever possible.
- Private functions/templates in each module are hidden by `local:` prefix (XSLT) or `%private` annotation (XQuery).
- `utils-library-at` parameter for XQuery recognizes only `#none`. (Noted in #1121)
  I guess probably nobody is actively using this parameter...

### CODE REVIEW

**Comment by AirQuick** [comment]
@galtm 
I don't think you want to review each line. (This PR is basically just a "copy and paste" work anyway.)
But it would be appreciated if you could review the general strategy here.

**Comment by galtm** [comment]
> @galtm
> I don't think you want to review each line. (This PR is basically just a "cut and paste" work anyway.)
> But it would be appreciated if you could review the general strategy here.

@AirQuick : The general strategy looks great. Thanks for forging ahead with this and for the clear summary in the PR description! Besides reading that, I also took a quick look at the files and diffs. Do you want me to enter my review now, or are you planning further commits that I should wait for?

**Comment by AirQuick** [comment]
Thanks @galtm 
You're more than welcome to enter your review now!

**Comment by AirQuick** [comment]
Thanks @galtm , I'm merging this.
I'm opening two more pull requests to complete #948.

**Pull request merged**
