### PR TITLE
More reliable DEL and RMDIR in xspec-bat.cmd 

### PR DESCRIPTION
**Pull request by AirQuick**
`xspec-bat.cmd` (a test script for Windows) sometimes uses DEL and RMDIR commands and checks their return value.
But [DEL](https://stackoverflow.com/q/22953027) and [RMDIR](https://stackoverflow.com/q/11137702) return `0` as long as the parameter is valid, even if the file operation has failed.

This pull request changes the call to DEL and RMDIR. Instead of checking their return value, `xspec-bat.cmd` now checks the actual result.

No code change in XSpec core.

---

This pull request derives from #248. So needs to be handled after that.

### CODE REVIEW

**Comment by cirulls** [comment]
@AirQuick: sorry for not being very active in the past weeks, reviewing your (many!) pull request is still my priority but I struggled to find time in September and keep up with your sterling work. It should be a bit better from next week. I suggest you go ahead with merging one pull request per day for the moment (that's my aim as well) so that you can keep on working on XSpec without accumulating too many changes. I would be grateful if you could start from the pull requests that do not touch the XSpec code (things like tests and cosmetic changes), I would still like that changes in the XSpec code are reviewed and approved by at least another contributor (not necessarily me). I hope this suits you - if not let me know!

**Comment by AirQuick** [comment]
@cirulls 
Thanks for all the effort. I'll start merging.
Fortunately the changes worth reviewing are from #266 and onward.
I believe the pull requests up to #265 are safe ones as commented in each.

**Comment by AirQuick** [comment]
@cirulls 
Merged this.

**Comment by vincentml** [comment]
@AirQuick 
I had hoped to review your recent pull requests, but I am sorry that I've not had time to do thorough reviews. I have not seen anything to cause concern in a light read through.

**Comment by AirQuick** [comment]
@vincentml 
Thank you for the review all the time. Sorry I had to close some pull requests prematurely. Whenever I added tests for one issue, I found another issue... Eventually I wasn't able to maintain dependencies between the pull requests.
Now that I have too many pull requests, I'm not sure if there is a specific one which interests you. But if you happen to find one, please review it anytime. That's really much appreciated.

**Comment by cirulls** [comment]
I agree. If other people are interested in reviewing existing pull requests, please do not hesitate to do so. Feel free to contact me if anyone needs some guidelines about reviewing pull requests for XSpec, I'll be happy to provide some guidance.

**Comment by AirQuick** [comment]
@cirulls 
In the draft relnote this is in **New features**, but it should probably be moved to **Tests**.

**Comment by cirulls** [comment]
@AirQuick : I moved it to Tests, thanks for spotting it. I'm going to do the official release tomorrow (Sunday), as far as I am concerned everything is ready.

**Pull request merged**
