### PR TITLE
feat(xslt): code coverage for Saxon 12.4+

### LINKED ISSUE #852: Code Coverage doesn't work on Saxon 10
http://www.saxonica.com/documentation/index.html#!changes/spi/9.9.1-10.0
> The mechanism supporting execution tracing (including the -T and -TP options on the command line) has been substantially revamped

### PR DESCRIPTION
**Pull request by AirQuick**
Closes #852 

With this change, Code Coverage now works on Saxon 12.4 or later.

Code Coverage doesn't work on all the older Saxon versions:
- Saxon 10.0 - 12.3: due to https://saxonica.plan.io/issues/6223
- Saxon 9.9: due to a breaking change on Saxon 10 (https://github.com/xspec/xspec/issues/852#issue-583897450)

### Known Regression

Code Coverage for `tutorial/escape-for-regex.xspec` marks a [`xsl:sequence`](https://github.com/xspec/xspec/blob/3140dd10e52b3733d5f272b0e1f0e92b280699bf/tutorial/escape-for-regex.xsl#L16-L21) as **missed**, while the current `master` branch (with Saxon 9.9) marks it as **hit**.
Saxon 12.4 (even with `-opt:0`)  does not notify the trace listener when entering the line 21. In such a case, XSpec can do some [guess](https://github.com/xspec/xspec/blob/3140dd10e52b3733d5f272b0e1f0e92b280699bf/src/reporter/coverage-report.xsl#L361-L378) afterward. But it doesn't help in this `xsl:sequence` case.

### CODE REVIEW

**Comment by galtm** [comment]
It seems that Code Coverage doesn't work for tests that use`run-as="external"`, with either Saxon 12.4 (code from this PR branch) or Saxon 9.9.1.8 (code from master branch). In both Saxon versions, I get different traces that aren't well-formed. I created a small test case outside XSpec and logged this issue with Saxonica: https://saxonica.plan.io/issues/6302

This doesn't mean that the problem in #746 has returned with Saxon 12.4. The sample files in #746 produce a code coverage report with Saxon 12.4 when the test doesn't use `run-as="external"`. But they don't produce a code coverage report when the test is changed to use `run-as="external"`.

**Comment by cmarchand** [comment]
Michael Kay give me some corrections on the `XSLTCoverageTraceListener.java` that I've never pushed back to xspec project.

I had the same problem, some instructions where never hit, although they should have been, that's why I've never puhsed this back.

I'm gonna compare this PR with Michael's code and comment it back...

**Comment by galtm** [comment]
Issues reported to Saxonica related to traces:

- https://saxonica.plan.io/issues/6295 (marked as resolved but not released yet)
- https://saxonica.plan.io/issues/6307
- https://saxonica.plan.io/issues/6302 (mentioned in my earlier comment)

**Comment by cmarchand** [comment]
Nice job @AirQuick for this PR. Your `java/com/jenitennison/xslt/tests/XSLTCoverageTraceListener.java` contains all patches from MK !

**Review by cmarchand — APPROVED** [review]

**Comment by galtm** [comment]
I want to merge this PR, but I also want to buy us some time to determine a solution for #1893 without having AppVeyor fail every time after code coverage switches from Saxon 9 to Saxon 12. (AppVeyor uses Saxon 12.) My concern is that constant failures could mask new non-Maven issues that we should pay attention to.

So, I'm going to make AppVeyor skip the Maven operations temporarily. I'm not sure whether it's better to push a new commit to this PR or use a separate PR. I'll try this PR first, so that if all goes well, this PR will pass all its checks instead of having a known failure that doesn't get fixed until the next PR.

**Comment by galtm** [comment]
@AirQuick : Thanks a lot for making this important update before taking a break! Hope to see you back in this repo soon.

**Pull request merged**
