### PR TITLE
fix(report): add getLocation method to trace listener

### PR DESCRIPTION
**Pull request by galtm**
Fixes the getLocation part of #1971, for use with Saxon 12.4 or 12.5. (This repo currently tests with 12.4.)

This pull request does not implement `-Tlevel:high`, as that part of the discussion in #1971 was moved to #1982.

This pull request is a draft. I plan to investigate the connection between this change and the list of untraceable elements that is part of the logic for the **Use Child Data** (a.k.a. **Use Descendant Data**) rule, so I might add more commits in the coming week.

@birdya22, do the Java changes look correct? I tried to follow your description in #1971 but I don't really understand the Java listener code.

### CODE REVIEW

**Comment by birdya22** [comment]
For the Java code, I had basically done the same changes locally, so they look ok to me.

**Comment by galtm** [comment]
> I plan to investigate the connection between this change and the list of untraceable elements that is part of the logic for the **Use Child Data** (a.k.a. **Use Descendant Data**) rule

I brought this pull request up to date after having merged a few others, but the task cited above is still on my to-do l ist.

**Comment by galtm** [comment]
> > I plan to investigate the connection between this change and the list of untraceable elements that is part of the logic for the **Use Child Data** (a.k.a. **Use Descendant Data**) rule
> 
> I brought this pull request up to date after having merged a few others, but the task cited above is still on my to-do l ist.

I'm inclined to leave the list of untraceable elements as is. While `getLocation` corrects some of the hits in the trace, some of those same elements (like `xsl:perform-sort`) then stop being traced in Saxon 12.5. Erring on the side of caution means leaving things on the list of untraceable elements rather than taking them off, because 'missed' instead of 'unknown' can be simply incorrect whereas 'unknown' instead of 'missed' expresses uncertainty.

I'm going to mark this pull request "ready for review".

**Comment by galtm** [comment]
I'll merge this pull request soon, as the only substantive changes are in the Java code that @birdya22 has already reviewed. After that, I'll make a pull request for #1920 based on https://github.com/xspec/xspec/pull/1978#issuecomment-2242145181.

**Pull request merged**
