### PR TITLE
build(maven): skip compiling precompiled Java

### PR DESCRIPTION
**Pull request by AirQuick**
Java classes are already compiled. This pull request skips compiling them.

I ran `mvn clean package -P release` and verified these:

- All [the tests](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally) are pass when these paths are replaced with the `xspec-2.0-SNAPSHOT.jar` file path:
  - [`xspec.sh` classpath](https://github.com/xspec/xspec/blob/788bd66d6ea164ee3e47b88db621497f16468098/bin/xspec.sh#L162)
  - [`compile` target classpath in `build.xml`](https://github.com/xspec/xspec/blob/788bd66d6ea164ee3e47b88db621497f16468098/build.xml#L416)
  - [`report-coverage` target classpath in `build.xml`](https://github.com/xspec/xspec/blob/788bd66d6ea164ee3e47b88db621497f16468098/build.xml#L478)
  - [`line-number_disabled.xspec` classpath](https://github.com/xspec/xspec/blob/master/test/line-number_disabled.xspec#L2)
  - [`line-number_enabled.xspec` classpath](https://github.com/xspec/xspec/blob/788bd66d6ea164ee3e47b88db621497f16468098/test/line-number_enabled.xspec#L3)
- `xspec-2.0-SNAPSHOT-javadoc.jar` and `xspec-2.0-SNAPSHOT-sources.jar` are essentially the same as the current `master` branch.

### CODE REVIEW

**Comment by AirQuick** [comment]
XSpec is tested regularly with the precompiled `*.class` files. I thought shipping the Maven artifact with them would be safer than shipping with untested recompiled files.
Can't we just define `Automatic-Module-Name` entry in `MANIFEST.MF` instead of recompiling with `module-info.class`?

**Comment by AirQuick** [comment]
> `*.java` files are source files, and must be build by build process
> `*.class` files are built files, and should not be commit in git repository.

That would definitely be true if XSpec were a Java project. Recall, however, XSpec is not a Java project but an XSLT (+ XQuery + Schematron) project. From the viewpoint of XSpec, files in `/java` are supplementary runtime components. For that reason, it's unlikely that XSpec will have a build process in the short term. Requiring a Java development environment will be too much for casual contributors.

**Comment by AirQuick** [comment]
> Can't we just define `Automatic-Module-Name` entry in `MANIFEST.MF` instead of recompiling with `module-info.class`?

Or even the default automatic module (`xspec`) without `Automatic-Module-Name` entry.

**Comment by cmarchand** [comment]
Ok, let add an `Automatic-Module-Name` in `MANIFEST.MF`. I vote for `io.xspec.xspec.xsl-impl'...

**Comment by AirQuick** [comment]
Thanks @cmarchand 

Added `Automatic-Module-Name` in 7d0c562bd867290edb497da0b18eff616ccbb503.
I set `io.xspec.xspec.impl` just because the package may include non-XSL resources.

I built `xspec-2.0-SNAPSHOT.jar` by running `mvn clean package -P release` on this pr branch and tested it with [an experimental code](https://github.com/xspec/xspec-maven-plugin-1/issues/46#issuecomment-621032315) on Java 11. It identified the `pom.properties` in the package successfully. So I presume the module name is working fine: 

```console
$ java -cp classes -p xspec-2.0-SNAPSHOT.jar --add-modules io.xspec.xspec.impl fr.jmdoudoux.dej.java.ModuleScan
...
**io.xspec.xspec.impl
META-INF/maven/io.xspec/xspec/pom.properties
```

**Comment by AirQuick** [comment]
Now that this branch tests Code Coverage with the jar file built by Maven on Java 8/11 on Linux/Windows/macOS on every CI system of ours and also has the automatic module name, I presume it's better than the current master. I'm merging this. Feel free to submit further changes.

**Pull request merged**
