### PR TITLE
build: release v3.1.2

### PR DESCRIPTION
**Pull request by galtm**
This pull request is for the checklist item in #1912 that says, "Create a pull request replacing `-SNAPSHOT` with the number, _num_, in `pom.xml` and the Oxygen add-on. Merge it into master".

It increments the version numbers to make the official stable release of v3.1. (technically v3.1.2, based on #940).

I tested the Oxygen add-on in Oxygen 26.1 using https://github.com/galtm/xspec/raw/v3.1.2/oxygen-addon.xml.

### CODE REVIEW

**Comment by galtm** [comment]
For reference, the analogous changes for v3.0 were #1904 and #1910.

**Comment by galtm** [comment]
@cmarchand , do you have time to review this change in the next couple of days?

**Comment by cmarchand** [comment]
I was OFF this week-end, ut now back on tracks.

Let me 8 hours, I will work on this this evening.

**Review by cmarchand — APPROVED** [review]
Nice, everything perfect

**Comment by galtm** [comment]
> Nice, everything perfect

Thanks for your timely review!

**Pull request merged**
