### PR TITLE
Regression test for code coverage

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #325. So needs to be handled after that.

---

This pull request enables regression test (`[XSpec]/test/*.xspec`) for the code coverage.
The tests are enabled only when Saxon is capable of the code coverage. So they are skipped on Travis and AppVeyor. They are enabled automatically, if you're running the tests on your machine with Saxon license.

### Running tests on oXygen
1. Open `[XSepc]/test/ant/build.xml` in oXygen.
1. In the **Transformation Scenarios** pane, select **ANT (with Saxon 9 EE XSLT support)** and apply it. (You may want to duplicate it and set `-silent` in **Additional arguments**.)

### Running tests on terminal

Here's what I tested on my local machine.

1. Do `set SAXON_JAR=\path\to\saxon9he.jar`. (Saxon-HE)
1. Run `run-xspec-tests-ant.cmd -silent` in `[XSepc]/test/`.
    Must pass [skipping](https://travis-ci.org/AirQuick/xspec/jobs/423908134#L1493) `xspec-215.xspec`.

1. Do `set SAXON_JAR=\path\to\saxon9ee.jar`. (Saxon-EE 9.**7**)
    `saxon9pe.jar` (Saxon-PE) should be fine too, but I haven't tested.
1. Run `run-xspec-tests-ant.cmd -silent`.
    Must pass including `xspec-215.xspec`.

1. Do `set SAXON_JAR=\path\to\saxon9ee.jar`. (Saxon-EE 9.**8**.0.14)
1. Run `run-xspec-tests-ant.cmd -silent`.
    Must fail at `xspec-215.xspec`. (Known issue of Saxon 9.8)

Repeat the same steps using `run-xspec-tests-ant.sh` on Ubuntu.

### How it works

1. `[XSepc]/test/ant/build.xml` [checks](https://github.com/xspec/xspec/blob/daa58a978ce2b90324bcc5a553939a6569974542/test/ant/build.xml#L14-L18) to see if the XSLT processor is capable of the code coverage. This information is [propagated](https://github.com/xspec/xspec/blob/daa58a978ce2b90324bcc5a553939a6569974542/test/ant/build.xml#L31-L32) to `[XSepc]/test/ant/worker/generate.xsl`.
1. While inspecting `[XSepc]/test/*.xspec`, `generate.xsl` [searches](https://github.com/xspec/xspec/blob/daa58a978ce2b90324bcc5a553939a6569974542/test/ant/worker/generate.xsl#L62-L63) for `<?xspec-test enable-coverage?>`. If the `enable-coverage` is found, `generate.xsl` does either of the followings.
    * [Sets](https://github.com/xspec/xspec/blob/daa58a978ce2b90324bcc5a553939a6569974542/test/ant/worker/generate.xsl#L99) the Ant property `xspec.coverage.enabled=true` for the `.xspec` file, if the XSLT processor is capable of the code coverage.
    * [Skips](https://github.com/xspec/xspec/blob/daa58a978ce2b90324bcc5a553939a6569974542/test/ant/worker/generate.xsl#L67-L75) the `.xspec` file, if the processor is not capable.

### CODE REVIEW

**Comment by AirQuick** [comment]
@cirulls 
Merged this improvement of test. Code coverage is now covered by the test suite. (Skipped on our [Travis](https://travis-ci.org/xspec/xspec/jobs/493556663#L1601) and [AppVeyor](https://ci.appveyor.com/project/xspec/xspec/builds/22387551/job/k3l72g424i420rcv#L472).)

@galtm 
#224 is now tested by `test/run-xspec-tests-ant.*`. Just FYI.

**Comment by AirQuick** [comment]
Updated [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/b75091047a83c3dfa8cb8a7dd18c623479a6a6d6...3bd587881748aef96e577d7c7dff1d92baa4eec3) to mention that oXygen can be used in place of `test/run-xspec-tests-ant.*`.

**Comment by galtm** [comment]
> Updated [Wiki](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/b75091047a83c3dfa8cb8a7dd18c623479a6a6d6...3bd587881748aef96e577d7c7dff1d92baa4eec3) to mention that oXygen can be used in place of `test/run-xspec-tests-ant.*`.

Nice update. Can you just change XSepc to XSpec in "Open [XSepc]/test/ant/build.xml in oXygen."?

**Comment by galtm** [comment]
> #224 is now tested by `test/run-xspec-tests-ant.*`. Just FYI.

Great!

**Comment by AirQuick** [comment]
> XSepc

[Fixed](https://github.com/xspec/xspec/wiki/How-to-Run-the-Test-Suite-Locally/_compare/3bd587881748aef96e577d7c7dff1d92baa4eec3...f92d861769112725a8217aefc30692f3e3fbc92b). Thanks for spotting it.

**Comment by cirulls** [comment]
I added this to the release notes (sections test and documentation).

**Pull request merged**
