### PR TITLE
add XProc harness for Saxon from v0.4.0

### PR DESCRIPTION
**Pull request by cirulls**
## Summary

This pull request is part of the code review for #103 and addresses the XProc harness for Saxon. See https://github.com/xspec/xspec/pull/103#issuecomment-286272902 for details. This pull request has been approved in https://github.com/xspec/xspec/pull/103#issuecomment-286288272.

## Why

The XProc harness was reverted to v0.3.0 in https://github.com/xspec/xspec/commit/ad6b0412afdf9f95feeb5b6c0e99804fa34d7bfc because it didn't seem to work. @fgeorges fixed this as part of #103 and provided information on how to run it so that the XProc harness implemented in v0.4.0-RC can be now used.

## What has changed
The library ```harness-lib.xpl``` is used for this XProc harness and can be re-used for other harnesses. One of the major changes from v0.3.0 is the use of the ```-p``` option in front of the parameter ```xspec-home```, this is required to run the harness correctly and needs to be added to the documentation. For more information see https://github.com/xspec/xspec/pull/103#issuecomment-286272902.

### CODE REVIEW

**Comment by fgeorges** [comment]
@cirulls This PR is red. I guess you need to fix it first?

**Comment by cirulls** [comment]
Yes, I think it is failing because the ```master``` branch is currently red. I will first merge #101 to get the test green again and then merge this pull request.

**Comment by cirulls** [comment]
After merging both #101 and this pull request tests are back to green on [Travis](https://travis-ci.org/xspec/xspec/builds/211363074) and [AppVeyor](https://ci.appveyor.com/project/xspec/xspec/build/1.0.163).

**Comment by fgeorges** [comment]
This PR is now displayed as "merged".  So there is nothing to do anymore, right?

**Comment by fgeorges** [comment]
I guess I misunderstood, as `master` does not include my harness changes.

I honesty do not understand what is going on.  It looks like some of my changes of #103 have found their way to master, but not all (I mean, even only a part of the changes WRT harnesses).

**Comment by cirulls** [comment]
> It looks like some of my changes of #103 have found their way to master, but not all 

That's correct. As discussed in #103, I'm going to push parts of your code to ```master``` as soon as I review them. This allows me to push smaller changes to ```master``` and update the documentation and the test suite as I go along. For now I have only reviewed the XProc harness for Saxon which is [currently on master](https://github.com/xspec/xspec/tree/master/src/harnesses/saxon) together with [harness-lib.xpl](https://github.com/xspec/xspec/blob/master/src/harnesses/harness-lib.xpl). As I review the next XProc harness, I will follow the same procedure I used here.

**Comment by fgeorges** [comment]
But there is a dependency on the harness lib from the other harnesses.  These changes go together.  I'd be very surprised they are not broken on master then.

**Comment by cirulls** [comment]
The other harnesses are still on v0.3.0 and do not import ```harness-lib.xpl```, see for example [basex-xquery-harness.xproc](https://github.com/xspec/xspec/blob/master/src/harnesses/basex/basex-xquery-harness.xproc).

**Pull request merged**
