### PR TITLE
feat: extend $x:context variable beyond x:expect

### PR DESCRIPTION
**Pull request by galtm**
This pull request builds on #1841 by making `$x:context` available in more situations -- ideally, everywhere a context has been defined or inherited, but not inside `<x:context>` itself.

### CODE REVIEW

**Comment by galtm** [comment]
I didn't like my original implementation in e1fd44423d9364c7e403745a92597bb5dd0ee989, so I used a different approach in d1147f7589e30512973198b5e3a36bb920bd2484.

**Comment by galtm** [comment]
There was a nontrivial merge conflict with #1780. At first, resolving the conflict added a lot of intermediate commits to the list of commits in this PR and made the commit list and diffs noisy. To address that, I rebased the commits specific to this PR against the master branch and force-pushed. (@cmarchand : Something I did to resolve the merge conflict apparently made GitHub assign you as reviewer. You're welcome to review this, but don't feel obligated if it's not an area of the code base that you're familiar enough with.)

Resolving the merge conflict added one extra commit that's specific to this PR: 1d48f941adbfe6e71af5418d30809eff1f3039b1. This PR defines `$x:context` earlier, but it's sometimes earlier in an inheritance chain than when the SUT is ready to run, so I had to conditionalize the error checking for an empty context. For an example where it matters, see the "Parent has mode" scenario in `test/x-context.xspec`.

**Comment by cmarchand** [comment]
I'm not at all familiar with this part of code ! It'll be difficult for me to have any opinion on this !

I let you decide what to do !

**Comment by galtm** [comment]
> I'm not at all familiar with this part of code ! It'll be difficult for me to have any opinion on this !
> 
> I let you decide what to do !

No problem. It was some automatic operation that brought you into this in the first place.

**Pull request merged**
