### PR TITLE
added java/ path to compiler, and Saxon dependency, to compiler XSLTC…

### PR DESCRIPTION
**Pull request by cmarchand**
PR for issue #414 . This should be integrated into a fix branch for release 1.1.0, and then merged to master

### CODE REVIEW

**Comment by cirulls** [comment]
@cmarchand : thanks for noticing this. As the `master` branch of XSpec has changed since your previous work on the `pom.xml` file, could you please [merge or rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) your branch on the latest `master` branch of XSpec? As you can see above, the test suite on AppVeoyor and Travis cannot be executed because of the conflict. 

Also, following our discussion in [here](https://github.com/xspec/xspec/pull/402#issuecomment-430520323), wouldn't it be appropriate to change the version to `1.2.0-SNAPSHOT` in the pom file? Or do you need a non snapshot version? I'm asking this because XSpec v1.1.1 was never released, I just would like to keep version numbering consistent.

**Comment by cmarchand** [comment]
My opinion was to create a hot-fix branch, from 1.1.0 tag, apply modifications to pom to include class, and publish a 1.1.1, which is exactly the same as 1.1.0 plus class in. Hence, we just change the fix number, as we do not change anything else.
Once 1.1.1 published, rebase / merge the hot-fix branch in master, to include fix in future 1.2.0-SNAPSHOT.
My pull-request has been created on a [fix_jar_content](https://github.com/cmarchand/xspec/tree/fix_jar_content) branch, and I wanted to add this branch to main repo.

**Comment by cirulls** [comment]
@cmarchand: sorry for my silence on this issue. It would be great to address the issue you highlighted in this pull request for the release of XSpec v1.2.0. I would suggest to create a similar pull request just before v1.2.0 is due to be released, you can track the progress on the release under [Projects](https://github.com/xspec/xspec/projects/3). What do you think?

**Comment by cmarchand** [comment]
There is no need for a new pull-request. Just merge this one, and change the version in pom to resolve the conflict.

**Comment by cmarchand** [comment]
@cirulls : how can I look at failed checks ?

**Comment by cirulls** [comment]
> There is no need for a new pull-request. Just merge this one, and change the version in pom to resolve the conflict.

Good point! I can resolve the conflict and update it with the correct version, no problem.

Just to be clear about the new value and the workflow for these changes: 

1. Following our conversation in [here](https://github.com/xspec/xspec/pull/402#issuecomment-430520323), I reckon I could change the snapshot version to `<version>1.2.0-SNAPSHOT</version>` right now and merge it immediately into `master` (the snapshot version is the development version leading to the official release version v1.2.0 according to [this maven guide](https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version)). 
2. Just before the official release XSpec v1.2.0, we create another pull request with `<version>1.2.0</version>` in the `pom.xml` file. This is the official release version. This pull request will be the last pull request to be merged into master before the release.
3. As soon as we start development on XSpec v1.3.0 (typically few days later after the release of v1.2.0), we can create another pull request with `<version>1.3.0-SNAPSHOT</version>`. 

Is this workflow ok for you? 

> how can I look at failed checks ?

A link to failed checks is usually displayed under AppVeyor or Travis close to the red cross but this failed check occurred few months ago and it may not be available any more. I reckon if we resolve the conflict new checks in AppVeyor and Travis will automatically trigger and we can inspect them in case they failed.

**Comment by cmarchand** [comment]
It's perfect to me.
May I suggest, once 1.2.0 release is out, to create a branch 1.2_fixups, to add in fixups that should be published as 1.2.x, without any new 1.3 devs ? Hence, it'll be easy to propose patches and fixup, that could also be merged in master, but that can be easily published directly.

**Pull request merged**
