### PR TITLE
Fix issue 466 (XSpec occupies x: namespace prefix)

### LINKED ISSUE #466: XSpec occupies x: namespace prefix
**XSpec** (Note `t` and `x` namespace prefixes.)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<t:description query="x-urn:test:do-nothing" query-at="do-nothing.xquery"
	stylesheet="do-nothing.xsl" xmlns:do-nothing="x-urn:test:do-nothing"
	xmlns:t="http://www.jenitennison.com/xslt/xspec" xmlns:x="my-namespace">
	<t:scenario label="Using x: prefix in user-content">
		<t:call function="name">
			<t:param>
				<x:element />
			</t:param>
		</t:call>
		<t:expect label="should be possible" select="'x:element'" />
	</t:scenario>
</t:description>
```

**XSLT**
```console
...
Creating Test Stylesheet...
...
Cannot create two namespace nodes with the same prefix mapped to different URIs (prefix=x, URI=my-namespace, URI=http://www.jenitennison.com/xslt/xspec)

*** Error compiling the test suite
```

**XQuery**
```console
...
Running Tests...
Static error on line 30 column 50 of test.xq:
  XPST0008: Variable $t:result has not been declared
Static error on line 1 column 22 of test.xq:
  XPST0008: Variable $local:successful has not been declared
Static error(s) in query

*** Error running the test suite
```

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #471. So needs to be handled after that.

---

Fixes #466

* 3669444f72a5ce5eab83aeef2ba45e5c5c01db28 makes the existing XQuery compiler's `$xspec-prefix` available to the XSLT compiler as well
* d5aec1fc35ba31e0e0db8653fd0643e6820e985e defines a helper function `x:xspec-name()` which makes use of `$xspec-prefix`
* 6bdc0dd4088adbd1ea56db2936d07a29bd14a08e and other commits replace hardcoded `x:foo` with `x:xspec-name('foo')`

#### Test
* b1e6d150644ea323252ea3fd9f5addbdde1da40a uses `x:` in as many places as possible
* 6f0bb8830c968a3081934a07fe17b7b950d0ae34 and other commits are updated to expect `t:`

### CODE REVIEW

**Comment by AirQuick** [comment]
@galtm
You mentioned this PR in #475: https://github.com/xspec/xspec/blob/d9840e07d10e5158154a2a76a34a7d6715a1da4c/test/xspec-variable.xspec#L11-L13
Also this PR modifies the existing code here and there.
So I thought I'd better ask your review.

A few things to note:
* This change requires the XSpec authors to provide at least one prefix such as `xmlns:x="http://www.jenitennison.com/xslt/xspec"`. The default namespace (i.e. `xmlns="http://www.jenitennison.com/xslt/xspec"`) is not sufficient and is [excluded explicitly](https://github.com/xspec/xspec/commit/3669444f72a5ce5eab83aeef2ba45e5c5c01db28#diff-001d11aaadf3edf13d9a7c6cfc30b845R34). This limitation is new on XSLT (not new on XQuery). I thought nobody would be affected by this limitation. But now I know that at least one project (namely [SchXslt](https://github.com/schxslt/schxslt/tree/master/src/test/resources/spec)) will be affected. I'll submit another pull request to circumvent the limitation.
* (off-topic) I wrote [`XSpec had better provide a way (maybe an attribute in x:description) to define the source document`](https://github.com/xspec/xspec/blob/3669444f72a5ce5eab83aeef2ba45e5c5c01db28/test/generate-xspec-tests.xspec#L25-L26). But I don't exactly think so now. Currently I think that XSpec should provide `/x:description/x:global-context-item` element which uses `test:generate-variable-declaration` to define the global context item.

**Comment by AirQuick** [comment]
@galtm 
This will conflict with #475, but the conflict will be very trivial. Just FYI.

**Comment by AirQuick** [comment]
@cirulls , @galtm 
Merged this bug fix.
The known limitation will be addressed in #572. If you happen to find another issue, limitation or potential improvement, please file it separately.

**Comment by galtm** [comment]
> This will conflict with #475, but the conflict will be very trivial.

@AirQuick , I uploaded 13fa7881fe346d5103361b23d22a285723ad6f98 to #475.

**Comment by galtm** [comment]
> You mentioned this PR in #475:

I plan to add something about XSpec variables in xspec-prefix-conflict*.xspec within the next week.

**Comment by AirQuick** [comment]
> The changes look good.

Thanks, @galtm. I added you to this PR row in the draft [relnote](https://github.com/xspec/xspec/releases). (ccing @cirulls )
Your review will also help when addressing #572. (I already have it in hand.)

**Comment by cirulls** [comment]
> I added you to this PR row in the draft relnote. 
@AirQuick and @galtm: thanks for adding the note and sorry for missing it.

**Comment by galtm** [comment]
@AirQuick  and @cirulls : Thanks, that's considerate of you to add me to the relnote.

**Comment by galtm** [comment]
> add something about XSpec variables in xspec-prefix-conflict*.xspec

I just uploaded 10e0609d7e074e0f602981e3c8709c11b955b730 to PR#475.

**Comment by cirulls** [comment]
@galtm: if you contribute to a pull request (even just with comments or a review) you'll be featured in the release notes to acknowledge your contribution (if you have fine with that, of course).

**Comment by galtm** [comment]
> fine with that, of course

@cirulls : I'm fine with it, thanks. :)

**Pull request merged**
