### PR TITLE
Schema: Move node-selection's href and user-content into choice

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #306. So needs to be handled after that.

Obsoletes #171.

---

In the current schema, `node-selection` makes both `href` and `user-content` optional:
https://github.com/xspec/xspec/blob/5c87ec02cb2e645e4ed892a3e80329b4f8e9a033/src/schemas/xspec.rnc#L190-L195
https://github.com/xspec/xspec/blob/5c87ec02cb2e645e4ed892a3e80329b4f8e9a033/src/schemas/xspec.rnc#L215

So it allows these elements
```xml
<x:context href="uri">content</x:context>
```
```xml
<x:param href="uri" name="foo">content</x:param>
```
```xml
<x:expect href="uri" label="foo">content</x:expect>
```
which don't make sense.

As for `x:context`, the scenario is terminated:
https://github.com/xspec/xspec/blob/5c87ec02cb2e645e4ed892a3e80329b4f8e9a033/src/compiler/generate-xspec-tests.xsl#L125-L132

As for `x:param` and `x:expect`, content is ignored in favor of `@href`:
https://github.com/xspec/xspec/blob/5c87ec02cb2e645e4ed892a3e80329b4f8e9a033/src/compiler/generate-tests-helper.xsl#L51-L66

This pull request updates the schema to reflect it. The elements above are no longer allowed by the updated schema.

This pull request consists of three commits:
* 3c01377b68fd9fea10ccaed6b6106e9372824098 verifies that the implementation does select `href` over `user-content`.
* f654c1b2c569c93b74ec9518759251b2bbbe1d21 updates the schema.
* d2fc95907f0f5c804b3ce8ef4800bac5fc6f7169 verifies that the schema does detect violation.

### CODE REVIEW

**Comment by AirQuick** [comment]
Although this pull request contains a lot of commits for historical reasons, all that needs to be reviewed in the end is a set of commits mentioned in the initial comment:
> * 3c01377b68fd9fea10ccaed6b6106e9372824098 verifies that the implementation does select `href` over `user-content`.
> * f654c1b2c569c93b74ec9518759251b2bbbe1d21 updates the schema.
> * d2fc95907f0f5c804b3ce8ef4800bac5fc6f7169 verifies that the schema does detect violation.

**Comment by AirQuick** [comment]
Thanks @galtm for the review. It's very helpful.

If you're interested, `test/xspec.bats` is Bats for *nix. Its syntax is written in its doc (["Writing tests" section](https://github.com/bats-core/bats-core#writing-tests)).

So, in the commit, the test runs [Jing](https://github.com/relaxng/jing-trang) to validate `test/xspec-node-selection.xspec` using `src/schemas/xspec.rnc` schema. And then the test verifies that Jing outputs exactly 5 violation lines and that every line contains `-child-not-allowed`. The test result on Travis is [here](https://travis-ci.org/xspec/xspec/jobs/473646098#L1231).

`test/win-bats/collection.xml` is for Windows. Just a mimic of Bats. Its result on AppVeyor is [here](https://ci.appveyor.com/project/xspec/xspec/builds/21297181/job/clqm7mimsvy97a80#L323).

If you're not interested in d2fc95907f0f5c804b3ce8ef4800bac5fc6f7169, feel free to review it just shallowly.

**Comment by galtm** [comment]
> If you're interested,

Thanks for the background information, @AirQuick. You saved me some time. The tests look good.

**Comment by cirulls** [comment]
Thanks. I recorded it in the release notes as enhancement/new feature.

**Pull request merged**
