### PR TITLE
build: release v3.0.3

### PR DESCRIPTION
**Pull request by galtm**
This pull request is for the checklist item in #1890 that says, "Create a pull request incrementing the version (to 3.0 without -SNAPSHOT) in pom.xml and the Oxygen add-on, and merge it into master".

It increments the version numbers to make the official stable release of v3.0. (technically v3.0.3, based on https://github.com/xspec/xspec/issues/940).

I tested the Oxygen add-on in Oxygen 26.1 using `https://github.com/galtm/xspec/raw/rel_3-0-3/oxygen-addon.xml`.

### CODE REVIEW

**Comment by galtm** [comment]
For reference, the analogous change for v2.3 was #1781.

**Comment by cmarchand** [comment]
I'm on it...

**Review by cmarchand — APPROVED** [review]

**Comment by galtm** [comment]
> I'm on it...

Thanks for your review!

I'm planning to do the release on 4/16/24 unless there is some surprise.

**Comment by galtm** [comment]
The AppVeyor failure was a timeout after the 60 minute limit. I sanity-checked the log. All the bats tests passed. The XSpec unit test script was in the "t"s when the timeout happened, and everything that ran until that point also passed. (The XSpec unit tests and the end-to-end tests ran to completion on GitHub Actions.)

**Comment by galtm** [comment]
I rechecked the AppVeyor log after my latest commits. The failure was a timeout after the 60 minute limit. All the bats tests passed. The XSpec unit test script completed and everything passed. The end-to-end script was in progress when the timeout happened; in some cases, an XSpec test has a deliberate failure, but I see nothing in the log that looks like an error or unexpected failure. (The end-to-end tests ran to completion on GitHub Actions.)

**Comment by galtm** [comment]
- The upgrade from the add-on v3.0.2 was offered and v3.0.3 is working fine on Oxygen 26.1 build 2024031806.
- The maven-deploy workflow has been [completed](https://github.com/xspec/xspec/actions/runs/8726020000) and I verified the artifact using pom.xml in [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Maven#fetching-xspec-file-set-in-maven). I see the 3.0 listing [here](https://central.sonatype.com/artifact/io.xspec/xspec/versions).

However, I think I was supposed to use 3.0.3 in pom.xml instead of 3.0. Compare with https://github.com/xspec/xspec/pull/1293. I'll change it to 3.0.3 in a separate pull request.

**Comment by galtm** [comment]
> I'll change it to 3.0.3 in a separate pull request.

Done: #1910

**Pull request merged**
