### PR TITLE
Better test for saxon script (matches comment's claim)

### PR DESCRIPTION
**Pull request by hanshuebner**
Supersedes #112

### CODE REVIEW

**Comment by cirulls** [comment]
Thanks for the reviewed pull request. 

As @fgeorges suggested in https://github.com/xspec/xspec/pull/112#issuecomment-292734068, I think it would be safer to have

**Comment by hanshuebner** [comment]
I don't quite understand your comment.  Safer to have what?  What is safe?

**Comment by cirulls** [comment]
Sorry @hanshuebner, I hit enter while I was still writing my comment, my bad. The full comment is now in https://github.com/xspec/xspec/pull/121#issuecomment-294444476, let me know if there is anything unclear.

**Comment by hanshuebner** [comment]
I don't see what would be safer about the suggested approach. In the end, I
don't care, however. I would just like to be able to run xspec.

Am 17.04.2017 12:35 nachm. schrieb "Sandro Cirulli" <
notifications@github.com>:

**Comment by cirulls** [comment]
I believe adding ```grep "EXPath Packaging"```to the condition in your pull request is safer because you may have your own saxon script that has nothing to do with the EXPath Packaging system and without that check you won't be able to run XSpec correctly (see the example I mentioned in https://github.com/xspec/xspec/pull/121#issuecomment-294444476). This is mainly to keep compatibility with people who do use the EXPath Packaging, if you don't use it you shouldn't have problems in running XSpec as that condition is automatically skipped.

If you have problems in running XSpec as it is, check the installation documentation on the [wiki](https://github.com/xspec/xspec/wiki) or post which error you're getting to see if I can help debugging. Or let me know if I just misunderstood the last part of your comment.

**Comment by AirQuick** [comment]
> @AirQuick : I think it would be good to add something similar to the batch script in order to align them. I think at the moment the batch script is only displaying a message and is not checking the presence of the saxon script. What do you think?

* The commit history suggests that the batch script has never supported the EXPath Packaging.
* I can't test the batch script with the EXPath Packaging regularly, as I don't (and will probably never) use it.
* The EXPath Packaging does not seem to be popular enough to take the risk listed above.

For those reasons, I left it in [TODO](https://github.com/xspec/xspec/blob/9f28df6ecde65d6fad0798c8e35e6c14f271d239/bin/xspec.bat#L18) when [aligning](https://github.com/xspec/xspec/pull/28) the batch script with the shell script. (I believe it's the only functional difference between the batch script and the shell script.)
So at the moment I would like to leave the batch script as it is, until a need arises.

**Comment by hanshuebner** [comment]
Sandro,

I just need the code do what the comment says: check whether the saxon
command runs the expected wrapper. I don't need further help debugging. If
you feel that my simple patch is unsafe, please make it as safe as you
think it needs to be. With the current behavior, I cannot run xspec because
it mistakes the standard saxon command line wrapper that can be installed
on CentOS and Ubuntu to be the EXPath or whatever wrapper, which is just
wrong. It also ignores the SAXON_CP environment variable of any saxon
command is found.

Thanks,
Hans

Am 17.04.2017 12:58 nachm. schrieb "Sandro Cirulli" <
notifications@github.com>:

**Comment by fgeorges** [comment]
Thank you, @hanshuebner.  If I understand correctly:

- initially, the test was "is there any saxon script?"
- your fix tests "does the saxon script invoked with --help return 0?"
- the PR in #122 tests, in addition, "does the output of saxon --help contain the string EXPath repository", which is more precise, and presumably what @cirulls means by "safer"

That way, not only it will prevent the script to mix up between your script and the EXPath one, but also between any other saxon script with the --help option, which is quite common.

@cirulls If you agree with this, can you test #122 and merge it, so @hanshuebner can use it?

Thank you all.

**Comment by hanshuebner** [comment]
Yes, Florent, your description is correct. Thanks! Hans

Am 17.04.2017 5:27 nachm. schrieb "Florent Georges" <
notifications@github.com>:

**Comment by cirulls** [comment]
Thanks everybody for the clarifications. @hanshuebner, sorry for the misunderstanding, by safer I meant more precise as @fgeorges said.

@fgeorges, I left a comment in #122 (taken from testing @hanshuebner's pull request in https://github.com/xspec/xspec/pull/121#issuecomment-294444476).

**Comment by cirulls** [comment]
Please see #124.

**Pull request closed without merging**
