### PR TITLE
Test for base URI

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #345. So needs to be handled after that.

---

This pull request just adds some tests to ensure that the external files such as `x:import/@href` are loaded via the base URI.

* [`xml-base.xspec`](https://github.com/xspec/xspec/commit/3cf51bd0755014b1bb322ac368fff33335da3c5d#diff-28684f73e3d22163922c7d0298a57b13) is both for XQuery and XSLT
* [`xml-base_stylesheet.xspec`](https://github.com/xspec/xspec/commit/3cf51bd0755014b1bb322ac368fff33335da3c5d#diff-03c3f1dfd1382e28aa5bce8990cc93a7) is only for XSLT

### CODE REVIEW

**Comment by AirQuick** [comment]
@galtm 
Can you take a look at this change?
This change just ensures that various instances of `@href` are resolved with `@xml:base`.

Also, I think `x:variable` has `@href`. After merging this, please consider integrating `x:variable` into [`xml-base.xspec`](https://github.com/xspec/xspec/blob/2b8d1fa5f35d6e7e749a99dce6e7419f47834ee9/test/xml-base.xspec) in #475, like you have already done in [`xspec-node-selection.xspec`](https://github.com/xspec/xspec/pull/475/files#diff-e549ef6c558f2510d9d89e6980b0da48).

**Comment by galtm** [comment]
> `x:variable` has `@href`. After merging this, please consider integrating `x:variable` into [`xml-base.xspec`](https://github.com/xspec/xspec/blob/2b8d1fa5f35d6e7e749a99dce6e7419f47834ee9/test/xml-base.xspec) in #475

Sure. I was thinking of adding one scenario for /x:description/x:variable and one for //x:scenario/x:variable. Is it worthwhile for me to check the case where the variable definition uses `@select` in addition to `@href`, in addition to the case of `@href` by itself?

**Comment by AirQuick** [comment]
Thanks, @galtm.

> Is it worthwhile for me to check the case where the variable definition uses `@select` in addition to `@href`, in addition to the case of `@href` by itself?

I'm not quite sure... So please add any test cases as you find useful and let's see what happens.

@cirulls 
Merged this test cases.

**Comment by galtm** [comment]
> please add any test cases as you find useful and let's see what happens.

@AirQuick 
OK. I just uploaded https://github.com/xspec/xspec/pull/475/commits/1e13462dfc81cee7b98ada4168f66e2cfef45419.

**Pull request merged**
