### PR TITLE
Add Ant build support for XQuery

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #265. So needs to be handled after that.

---

This pull request allows to run XSpec tests for XQuery using Ant build script.

The new `test.type` value for XQuery is `q`. The command line argument is demonstrated in tests: 9335bed4dc5e4955a9d02fb08d1f9c80f4e0a1de

If you're testing this pull request with oXygen, you may want to replace `test.type` in the default transformation scenario with `${xpath_eval((doc('${currentFileURL}')/*:description/(@query,@schematron)/substring(name(),1,1), 't')[1])}`.

While working on this change, I found it difficult to decipher some of the code. So I

* provided annotations to properties and tasks
* renamed properties and tasks as self-descriptive as possible
* revised format and indent

That's why many lines are changed. But the fundamental logic has not been changed.

### Further work

* Update the documentation in wiki: Need to mention the new `test.type` value `q`.

### CODE REVIEW

**Comment by AirQuick** [comment]
@cirulls 
Thank you for the smooth handling of the new release.

Now, sorry to rush you, but if we could handle this PR up to #291 as quickly as possible, that would be welcomed, because

* #266 makes it possible to run XQuery on Ant or on oXygen, although XSpec's XQuery implementation is very limited
* #268 is a requested feature
* #269 runs XQuery tests regularly on Travis and AppVeyor
* #279 makes it possible to generate Code Coverage on Ant or on oXygen, although Code Coverage may be unstable until #354
* Leaving #284, #285, #286, #289, #291 opened will incur merge conflicts with the other people

**Comment by cirulls** [comment]
@AirQuick : Absolutely! I created a [project for release v1.2.0](https://github.com/xspec/xspec/projects/3) and added #266 as in Progress, feel free to add other issues and PRs in the relevant columns. I think I should be able to review #266 by the end of this week, I'll keep you posted.

**Comment by AirQuick** [comment]
Thanks, @cirulls !

Updated [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant#running-xquery-tests-on-ant
), though the update may not be visible until GitHub resolves [a certain problem](https://status.github.com/#2018-10-22)...

**Comment by AirQuick** [comment]
Thanks, @cirulls !

Updated [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant#running-xquery-tests-on-ant
), though the update may not be visible until GitHub resolves [a certain problem](https://status.github.com/#2018-10-22)...

**Comment by AirQuick** [comment]
Thanks, @cirulls !

Updated [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Ant#running-xquery-tests-on-ant
), though the update may not be visible until GitHub resolves [a certain problem](https://status.github.com/#2018-10-22)...

**Pull request merged**
