### PR TITLE
Use latest Saxon 9.6.0-10 for ci tests

### PR DESCRIPTION
**Pull request by tofi86**
Saxon 9.6 series got an update in December 2016

### CODE REVIEW

**Comment by cirulls** [comment]
Thanks for your pull request. Using Saxon 9.6.0-7 instead of 9.6.0-10 version was actually a choice made in #43:

> Although the latest 9.6 is 9.6.0.10, I chose 9.6.0.7 just because it's the one bundled currently in oXygen.

We can trigger tests for all three versions of Saxon, that would not be a problem. The only drawback is that running the test suite via AppVeyor for the Windows environment will take a bit longer (Travis doesn't have this problem as it runs tests in parallel).

I assign the review to @AirQuick as he (or she?) did the initial implementation for AppVeyor.

**Comment by tofi86** [comment]
> Using Saxon 9.6.0-7 instead of 9.6.0-10 version was actually a choice made in #43:

oh, okay... yeah, well, so it's upt to you and @AirQuick whether you want to accept this, test three versions or decline the PR...

**Comment by AirQuick** [comment]
While 9.6.0.8 was released in 2015-12, oXygen still sticks to 9.6.0.7 to date. So I (he) fancied 9.6.0.7 might be widely used. No other specific reason. It's ok to just move on to 9.6.0.10.

By the way, is Syncro Soft aware of this repository? Will they sooner or later consider updating XSpec in oXygen based on this repository?

**Comment by tofi86** [comment]
> By the way, is Syncro Soft aware of this repository? Will they sooner or later consider updating XSpec in oXygen based on this repository?

We (@paginagmbh) are an oXygen partner. I can give @georgebina a shout and will also write an email to their support team.

**Comment by cirulls** [comment]
> By the way, is Syncro Soft aware of this repository? Will they sooner or later consider updating XSpec in oXygen based on this repository?

Funny that you mention this, straight after the release I sent a message to [this Oxygen Forum](https://www.oxygenxml.com/forum/forum2.html) asking to try out the latest release and possibly integrate in the future. I'm waiting for the message approval, I'll post the link here when it's visible so you can follow their reply.

I don't mind testing for all three versions of Saxon as I would like to keep the Saxon version used by Oxygen. Which option would you prefer:

1. Run tests with Saxon 9.7.0-14, 9.6.0-7, and 9.6.0-10 (aka request changes to the pull request)
2. Run tests with Saxon 9.7.0-14 and 9.6.0-10 (aka accept the pull request)
2. Run tests with Saxon 9.7.0-14 and 9.6.0-7 (aka reject the pull request)

I'm fine with option 1. @tofi86 and @AirQuick : which option would you prefer?

**Comment by AirQuick** [comment]
I'm fine with 1.
If we go for 1 and if AppVeyor is annoyingly slow, I think we may retract 9.6.0-7 (or -10) only from AppVeyor.

**Comment by tofi86** [comment]
Okay, going to implement `#1`

**Comment by tofi86** [comment]
Done. Waiting for CI (timing) results…

**Comment by AirQuick** [comment]
Funny they went down 😮   https://appveyor.statuspage.io/

**Comment by tofi86** [comment]
hahaha, hope it wasn't me :joy:

**Comment by AirQuick** [comment]
@cirulls , can you cancel the [job](https://ci.appveyor.com/project/xspec/xspec/build/1.0.52)?
Maybe it is straying like [this](https://twitter.com/appveyor/status/820765896050229248).

**Comment by AirQuick** [comment]
The oXygen forum thread is now [visible](https://www.oxygenxml.com/forum/topic13959.html). Thank you for pinging them.

**Comment by cirulls** [comment]
I cancelled the hanging job, restarted a new build and tests are passing for all three versions of Saxon: https://ci.appveyor.com/project/xspec/xspec/build/1.0.56 It took about 5 minutes to run the test suite on AppVeyor. I guess it is fine but if it reaches 10 minutes in the future we should probably look at running tests in parallel on AppVeyor.

**Comment by cirulls** [comment]
> By the way, is Syncro Soft aware of this repository? Will they sooner or later consider updating XSpec in oXygen based on this repository?

Alex Jitianu from Oxygen replied @tofi86's email:

> Oxygen ships a quite old version of XSpec so we will definitely test the new version. If all goes well it will be present in Oxygen 19.0.

**Pull request merged**
