### PR TITLE
line-number function is from zenta-tools

### PR DESCRIPTION
**Pull request by magwas**
I understand this pull request is not mergeable as is.
My intention is to figure out what to do to make it acceptable upstream.
As the saxon namespace is not ours. We use another one, but  for the same functionality to avoid conflicts.

Also, we use the script below instead of `xspec.sh`. Any feedback on how to integrate that to the codebase is welcome.

```
#!/bin/bash
set -e
if [ "$1" = "-s" ]
then
	see=firefox
	shift
else
	see=true
fi

if [ "$1" = "-v" ]
then
	shift
	set -x
fi
basename=$(basename $1 .xspec)
dirname=$(dirname $1)
COVERAGE_XML=target/xspec/${dirname}/${basename}-coverage.xml
COVERAGE_CLASS=com.jenitennison.xslt.tests.XSLTCoverageTraceListener
COMPILED=target/xspec/${dirname}/${basename}-compiled.xsl
RESULT=target/xspec/${dirname}/${basename}-result.xml
RESULT_HTML=target/xspec/${dirname}/${basename}-result.html
COVERAGE_HTML=target/xspec/${dirname}/${basename}-coverage.html

CLASSPATH=/usr/share/zenta-tools/zenta-tools.jar:/usr/local/lib/xspec.jar

runner-with-coverage () {
java -cp $CLASSPATH -Dxspec.coverage.xml=${COVERAGE_XML} -Dxspec.xspecfile=${dirname}/${basename}.xspec org.rulez.magwas.zentatools.Main -r:org.rulez.magwas.zentatools.RelativeUriResolver -T:com.jenitennison.xslt.tests.XSLTCoverageTraceListener $@
}

runner () {
	java -cp $CLASSPATH org.rulez.magwas.zentatools.Main -r:org.rulez.magwas.zentatools.RelativeUriResolver $@
}

xspec=/usr/local/share/xspec/src
runner -o:$COMPILED -s:$1 -xsl:${xspec}/compiler/generate-xspec-tests.xsl
runner-with-coverage -o:$RESULT -xsl:$COMPILED '-it:{http://www.jenitennison.com/xslt/xspec}main'
runner -o:${RESULT_HTML} -s:$RESULT -a inline-css=true
runner -o:${COVERAGE_HTML} -s:${COVERAGE_XML} -xsl:${xspec}/reporter/coverage-report.xsl -l:on inline-css=true
$see ${RESULT_HTML} ${COVERAGE_HTML}
failed=$(java -cp /usr/share/zenta-tools/zenta-tools.jar net.sf.saxon.Query -s:$RESULT -qs:"declare namespace x='http://www.jenitennison.com/xslt/xspec';count(//x:test[@successful='false'])" '!method=text')
if [ $failed -gt 0 ]
then
	exit 1
fi

```

### CODE REVIEW

**Comment by AirQuick** [comment]
* Regarding the substitution of `saxon:line-number()`, doesn't [`xsl:function/@override`](https://www.w3.org/TR/xslt20/#element-function) work without modifying `src\reporter\coverage-report.xsl` directly? I haven't tried it, so just checking.
* Regarding `xspec.sh`, your goal is introducing `-s` to open the report in a web browser and `-v` to print script-debugging information?

**Comment by magwas** [comment]
>     * Regarding the substitution of `saxon:line-number()`, doesn't [`xsl:function/@override`](https://www.w3.org/TR/xslt20/#element-function) work without modifying `src\reporter\coverage-report.xsl` directly? I haven't tried it, so just checking.

By reading the standard it should work. The question now is where to place it?
As I understand the compiled sheet will import coverage-report.xsl, so that would mean that I should emit the override element or include the sheet containing it in compile time based on the xslt runner used.
Which solution (emit the code if needed, or use different toplevel template based on xslt runner) do you prefer?

> 
>     * Regarding `xspec.sh`, your goal is introducing `-s` to open the report in a web browser and `-v` to print script-debugging information?

The main reason was that xspec.sh have some underlying assumption which is not true in our setup, and it seemed that a greater refactor is needed to make it run with zenta-xslt-runner instead of the already supported xslt implementations, esp. when we do have a saxon lying around. We also don't need some of the functionalities supported (like XQuery and Schematron support).
So it seemed to be easier to prototype using our own script. On the long term it is arguably better to properly implement support for zenta-xslt-runner to xspec.sh, but honestly I am a bit lost here.

Other than that: yes, -v is meant to provide debug for the script itself, and -s is meant to launch a browser on the generated output. These will be easy modifications to the xspec.sh script (using something else instead of the already taken -s ), so that is not an important question beyond whether you would accept the functionality.

**Comment by AirQuick** [comment]
> By reading the standard it should work. The question now is where to place it?

How about making this small change (very similar to Ant [`build.xml`](https://github.com/xspec/xspec/blob/abbd6cf9cc283d8c3fa765210963b00605f9146d/build.xml#L103-L105)) in `xspec.sh`

```
@@ -301,6 +301,7 @@ RESULT=$TEST_DIR/$TARGET_FILE_NAME-result.xml
 HTML=$TEST_DIR/$TARGET_FILE_NAME-result.html
 JUNIT_RESULT=$TEST_DIR/$TARGET_FILE_NAME-junit.xml
 COVERAGE_CLASS=com.jenitennison.xslt.tests.XSLTCoverageTraceListener
+COVERAGE_REPORTER_XSL=$XSPEC_HOME/src/reporter/coverage-report.xsl
 
 if [ ! -d "$TEST_DIR" ]; then
     echo "Creating XSpec Directory at $TEST_DIR..."
@@ -453,7 +454,7 @@ if test -n "$COVERAGE"; then
     xslt -l:on \
         -o:"$COVERAGE_HTML" \
         -s:"$COVERAGE_XML" \
-        -xsl:"$XSPEC_HOME/src/reporter/coverage-report.xsl" \
+        -xsl:"$COVERAGE_REPORTER_XSL" \
         inline-css=true \
         || die "Error formatting the coverage report"
     echo "Report available at $COVERAGE_HTML"
```

so that you can write `your-coverage-report.xsl` where you have

```xslt
<xsl:stylesheet>
  <xsl:import href="path/to/xspec/src/reporter/coverage-report.xsl" />

  <xsl:function name="saxon:line-number" override="yes or no depending on your intention" >
    <xsl:param name="node" />
    <xsl:sequence select="zentatools:line-number($node)" />
  </xsl:function>
</xsl:stylesheet>
```

and run it like this?

```shell
export COVERAGE_REPORTER_XSL=path/to/your-coverage-report.xsl
xspec.sh -c test.xspec
```

> As I understand the compiled sheet will import coverage-report.xsl, so that would mean that I should emit the override element or include the sheet containing it in compile time based on the xslt runner used.

The compiled stylesheet does not use `coverage-report.xsl` at all. `coverage-report.xsl` is used after finishing running the compiled stylesheet.

**Comment by AirQuick** [comment]
> The main reason was that xspec.sh have some underlying assumption which is not true in our setup, and it seemed that a greater refactor is needed to make it run with zenta-xslt-runner instead of the already supported xslt implementations, esp. when we do have a saxon lying around. We also don't need some of the functionalities supported (like XQuery and Schematron support).

I don't know what `zenta-xslt-runner` is. But `xspec.sh` [calls](https://github.com/xspec/xspec/blob/abbd6cf9cc283d8c3fa765210963b00605f9146d/bin/xspec.sh#L58-L80) `saxon` script if found in `PATH`. So if you write your own `saxon` script, you can probably adapt or inject parameters in it, and invoke `zenta-xslt-runner` from it with the adapted/injected parameters.

**Comment by AirQuick** [comment]
* Regarding `saxon:line-number()`, I happened to submit #795 which replaces `saxon:line-number()` with our own implementation. That may eliminate your need to replace it with `zentatools:line-number()`.
* Regarding `-r:org.rulez.magwas.zentatools.RelativeUriResolver`, [`SAXON_CUSTOM_OPTIONS`](https://github.com/xspec/xspec/wiki/Environment-Variables) will be of help, if `-r` is required only by your stylesheet being tested and not required at compile time.
* Regarding `org.rulez.magwas.zentatools.Main`, I don't know why you need it, but depending on your goal, we may possibly consider replacing the hardcoded `net.sf.saxon.Transform` with an environment variable.

**Comment by AirQuick** [comment]
For https://github.com/xspec/xspec/pull/787#issuecomment-586696536, I opened #823.

**Comment by AirQuick** [comment]
Closing, as [`v1.6.0`](https://github.com/xspec/xspec/releases/tag/v1.6.0) no longer uses the `saxon` namespace in question. As for the other points, I think I've proposed alternate methods. Please feel free to open another pull request if you have better ideas. In that case, it would be appreciated if each pull request could handle a limited and specific idea.

**Pull request closed without merging**
