### PR TITLE
build(maven): remove pluginManagement from pom.xml

### PR DESCRIPTION
**Pull request by AirQuick**
`pom.xml` has `<pluginManagement>` but we have no parent/child pom. So I guess we can remove it for simplifying `pom.xml`.

I compared the JAR files generated by `mvn clean package -P release` with the current `master` branch and this PR branch, and verified that they were essentially the same: Only `pom.xml` and the timestamps in `.html` files were different.

### CODE REVIEW

**Comment by AirQuick** [comment]
Then, why not all the plugins are declared in `<pluginManagement>`?
Right now, some plugins are in `<pluginManagement>` and the others are not.

**Comment by cmarchand** [comment]
It is also a bad practice ! I'd should declare all plugins in `<pluginManagement />` section !

**Comment by AirQuick** [comment]
For example, in MRJar, [`maven-release-plugin`](https://github.com/cmarchand/maven-mrjar-demo/blob/ad5e7205940ee16fccdb7e677733a2dfc0481b14/pom.xml#L182-L185) is not in `<pluginManagement>`. It's against the best practice?

**Comment by cmarchand** [comment]
Yes, it is a bad practice. Actually, my `release` profile is always copied/pasted from another project, as using a parent pom is not always the best thing (mainly when you work in various organizations).

`maven-release-plugin` and `maven-enforcer-plugin` are used only in one place, and there is no chance they will be used elsewhere. `maven-javadoc-plugin` could be used in other profiles, and should be declared and configured in `pluginManagement`.

**Comment by AirQuick** [comment]
Likewise, no plugin is used in multiple places in XSpec `pom.xml`. So I thought it would be simpler to remove `<pluginManagement>` in this PR for the meantime. If any plugin is used in multiple places in the future, we will definitely put it in `<pluginManagement>`. What do you think?

**Comment by AirQuick** [comment]
> If any plugin is used in multiple places in the future, we will definitely put it in `<pluginManagement>`.

Added a note for it: e9c9e00d51174831f8c7c5ebb4b06e3e326bcb56

**Comment by cmarchand** [comment]
Ok for me.

**Pull request merged**
