### PR TITLE
Run unit test for XQuery

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #268. So needs to be handled after that.

This pull request obsoletes #187.

---

We have a test script `run-xspec-tests.*` for testing `test/*.xspec`. But it doesn't test XQuery.
This pull request tests XQuery/Schematron/XSLT on Travis and AppVeyor.

### Running tests on terminal

In order to test XQuery/Schematron/XSLT easily in a cross-platform way, I replaced `run-xspec-tests.*` in Travis/AppVeyor config with new `run-xspec-tests-ant.*`. (See [README](https://github.com/AirQuick/xspec/tree/test_xquery/test/ant) for details.)

As a side benefit, this new test scheme runs much faster than the classic `run-xspec-tests.*`:
* [79 seconds](https://travis-ci.org/AirQuick/xspec/jobs/414889128#L515) vs [255 seconds](https://travis-ci.org/AirQuick/xspec/jobs/413191902#L515) on Travis
* [104 seconds](https://ci.appveyor.com/project/AirQuick/xspec/build/528-test_xquery/job/1wimb8okerl6lgm5#L320) vs [317 seconds](https://ci.appveyor.com/project/AirQuick/xspec/build/506-saxon-custom-options/job/au5tjxv5m6e0t2es#L320) on AppVeyor

I kept the classic `run-xspec-tests.*` intact, for compatibility.

### Running tests on oXygen
1. Open `test/ant/build.xml` in oXygen.
1. In the **Transformation Scenarios** pane, select **ANT (with Saxon 9 EE XSLT support)** and apply it. (You may want to duplicate it and set `-silent` in **Additional arguments**.)

### CODE REVIEW

**Comment by AirQuick** [comment]
Any concern for this change?

**Comment by AirQuick** [comment]
@cirulls 
I'll be merging this shortly, unless a concern arises.

**Comment by cirulls** [comment]
@AirQuick: sorry for my late reply, I started reviewing this pull request but didn't finish it. I will complete the review on Sunday 18th November, please bear with me for a couple of days. Sorry for keeping you waiting!

**Comment by AirQuick** [comment]
> I think it could be useful to add few lines to the Ant documentation and point to the README file.

Added a section *[Using Ant to run multiple XSpec tests](https://github.com/xspec/xspec/wiki/Running-with-Ant#using-ant-to-run-multiple-xspec-tests)*.

**Comment by cirulls** [comment]
Thanks for updating the documentation. 

Just to confirm that I ran the test suite with ant on oXygen 20.0, I could see the option *ANT (with Saxon 9 EE XSLT support)* and I was able to run successfully the test suite via oXygen.

**Pull request merged**
