### PR TITLE
Issue/584

### PR DESCRIPTION
**Pull request by cmarchand**
Fix proposal for issue #584

### CODE REVIEW

**Comment by AirQuick** [comment]
Thanks, @cmarchand 
I tested `mvn install` and found `build.xml` in the target jar.

@nkutsche 
Is this fine with you?

**Comment by cmarchand** [comment]
It should also be present in xspec-xxx-sources.jar...

**Comment by AirQuick** [comment]
I confirmed that `mvn install -P release` generated `xspec-1.4.0-SNAPSHOT-sources.jar` containing `build.xml`.

**Comment by nkutsche** [comment]
> 
> Thanks, @cmarchand
> I tested `mvn install` and found `build.xml` in the target jar.
> 
> @nkutsche
> Is this fine with you? Since the jar's directory structure is shifted up from the repository, I'm not sure if it serves your purpose.

Hi, at first: thanks for your work!

Important for me was, that there in one Maven artifact which contains an *executable* build.xml. Maybe the description was not clear enough in that point. I'll have a look if this would be embeddable. Hope I can make it this weekend.

**Comment by cmarchand** [comment]
Have a look at this and tell us if it's ok for you.
https://oss.sonatype.org/content/repositories/snapshots/io/xspec/xspec/1.4.0-SNAPSHOT/xspec-1.4.0-20190820.123532-1.jar
Best,
Christophe

**Comment by nkutsche** [comment]
Hi,

the current build.xml has the following "hard coded" path including the `src` directory which does not exists in the jar.
That's what I found:
```
${xspec.project.dir}/src/reporter/format-xspec-report.xsl
${xspec.project.dir}/src/reporter/coverage-report.xsl
${xspec.project.dir}/src/reporter/junit-report.xsl
${xspec.project.dir}/src/ant/make-path.js
${xspec.project.dir}/src/schematron/iso-schematron/iso_dsdl_include.xsl
${xspec.project.dir}/src/schematron/iso-schematron/iso_abstract_expand.xsl
${xspec.project.dir}/src/schematron/generate-step3-wrapper.xsl
${xspec.project.dir}/src/schematron/schut-to-xspec.xsl
${xspec.project.dir}/src/compiler/${xspec.compiler.xsl}
```
Most of them are values of properties, so I think I could overwrite them. But some of them are directly used in e.g. `<saxon-xslt style=""/>`. To execute this `build.xml` I would need to wrap all subdirectories into a `src` folder.
To make it clean, I would like to introduce a property:

```
<property name="xspec.project.src" value="${xspec.project.dir}/src">
```

I would like to make a proposal. As far as I understand (I'm not so deep in Github as I would like) I need to create a pull request into [Christophes repository](https://github.com/cmarchand/xspec/tree/issue/584) to make my proposal visible to you, right?

**Comment by cmarchand** [comment]
If you clone my repo, you will create a pull request to my repo, and then I'll have to create a pull request to this one. It may work, but is complex.
So you'd better directly fork https://github.com/xspec/xspec into your account, then clone your own copy of repo, and then, and your pull request will fall into this repo.

**Comment by AirQuick** [comment]
> To make it clean, I would like to introduce a property

XSpec files expect the directory structure to start with the project root directory. They also expect another file to be found relatively, not only within the same 2nd level directory but also between any directories.
The project root directory is already specified indirectly with `xspec.project.dir`. I'm afraid introducing the 2nd level indirection would just complicate the overall maintenance.

Can't we just make the structure in jar to match the actual repo structure? For example, Oxygen's `[Oxygen installation dir]/frameworks/xspec/` dir has `build.xml` and `src` side by side, which matches the repo structure.

**Comment by nkutsche** [comment]
> The project root directory is already specified indirectly with xspec.project.dir. I'm afraid introducing the 2nd level indirection would just complicate the overall maintenance.
>
> Can't we just make the structure in jar to match the actual repo structure? For example, Oxygen's [Oxygen installation dir]/frameworks/xspec/ dir has build.xml and src side by side, which matches the repo structure.

I see your point, it was just an idea. If it is ok for you, I'm also fine with changing the jar structure. But I could imagine that it produces lot of work for those who use the jar currently. How about having two artifacts - one as it is now and one including the `build.xml` with the `src` directory?

**Comment by AirQuick** [comment]
Some use cases may need other directories:
* Taking Code Coverage using `build.xml` requires the `java` directory
* `src/reporter/format-xspec-report-folding.xsl` requires the `graphics` directory

**Comment by AirQuick** [comment]
What do you think, @cmarchand ?
If we can come up with a good solution in a few days, we can include this in v1.4.0. Otherwise, we'll just defer it.

**Comment by cmarchand** [comment]
I think we have different expectations on what should contain the jar.

IMO, jar should contain enough code to be embedded in other runners than default implementation. That's why I've created this jar, for xspec-maven-plugin.
Default distribution (i.e. zip/tar.gz files https://github.com/xspec/xspec/archive/v1.3.0.tar.gz) should be sufficient for @nkutsche needs, but is not available on maven.
Maybe we could replace the actual -source.jar deployed on maven by this zip file.

This implies to :
 - modify pom.xml to download published release file from github, based on naming convention
 - create release **first** on github, publish zip & tar.gz files on github, and then start maven publishing process.

This may be a problem if you think it's too complicated.

This solution is not a big deal, and can be quickly developed, it's only `pom.xml` config, and I can do it quickly.

**Comment by AirQuick** [comment]
So, for v1.4.0, let's release it without this pull request so that @cirulls can release it using the established procedure.

As for this pull request, we will be able to release a minor version as soon as @cmarchand and @nkutsche agree to a solution.

**Comment by nkutsche** [comment]
Hi guys,

sorry for my late reply. In fact, I wasn't sure if you need my input for @cmarchand proposal. But since it seems so, all I can just point out: It is exactly what I had in mind, when I wrote

> How about having two artifacts - one as it is now and one including the build.xml with the src directory?

Isn't it?

Regarding your concerns:

> For end-users as @nkutsche, it implies to add a <classifier>source</classifier> in their dependency declaration.
> 
> This may be a problem if you think it's too complicated.

As far as I know Maven, it is not unusual to have more than one artifact. And every time, when you have more then one artifact, you need such a `classifier`. So I'm pretty sure, that this should be feasable for each Maven developer.

**Pull request closed without merging**
