### PR TITLE
Fix Ant issue 633 (Nashorn engine is deprecated)

### LINKED ISSUE #633: Ant: Warning: Nashorn engine is planned to be removed from a future JDK release
`<scriptdef>` in Ant build file will need to be replaced with another method.
https://github.com/xspec/xspec/blob/4556cddf350f9658d67112f447cbc0b103023383/build.xml#L155-L159

```console
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode)
$ ant -lib SaxonEE9-9-1-5J/saxon9ee.jar -Dxspec.xml=tutorial/schematron/demo-01.xspec -Dtest.type=s
...
locate-schematron-file:
...
 [makepath] Warning: Nashorn engine is planned to be removed from a future JDK release
...
```

---

`<script>` is also used in [a test util](https://github.com/xspec/xspec/blob/4556cddf350f9658d67112f447cbc0b103023383/test/ant/worker/build-worker_util.xml#L81-L86), but it's just for optional time calculation. No problem to remove it.

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request fixes #633 by porting a custom Ant task from [JavaScript](https://github.com/xspec/xspec/blob/e19539062a32ce7424e4a24416498d6dd38a9c0f/src/ant/make-path.js) to Java

* 8594daa4e81976372801277be00dc8759021f2f1 reproduces #633 on Java 11: [Azure](https://xspec.visualstudio.com/xspec/_build/results?buildId=167), [Travis](https://travis-ci.org/xspec/xspec/builds/588645011)
* 0d278e0ffa7c9812a57d45a6c816a3f747575687 is the primary change

### CODE REVIEW

**Comment by AirQuick** [comment]
@nkutsche
It would be helpful if you could confirm this change fixes nkutsche/xspec-maven-plugin#1

**Comment by nkutsche** [comment]
> 
> 
> @nkutsche
> It would be helpful if you could confirm that this change solves [nkutsche/xspec-maven-plugin#1](https://github.com/nkutsche/xspec-maven-plugin/issues/1)

@AirQuick: yes it works! Using this PR I could run a Maven build on JDK 11.0.3. Using a previous XSpec version (1.3.0) it didn't worked. Great! Looking forward to it being released.😃

**Comment by AirQuick** [comment]
Thanks @nkutsche.
We now test on Java 11 (#637) and actively catch warnings (#642). Hopefully similar problems won't happen again.

@xspec/xspec 
This change contains a Java code. I don't want to depend on Java in the code base, but it seems there's no other way. Fortunately the code is responsible only for a rather trivial task.
Although I scarcely know Java, I tried following [an Ant's similar builtin task code](https://github.com/xspec/xspec/pull/644/files#diff-95bc24199f521fb2069d80862ecbf742R17) and I hope my resultant code is ok.

@cmarchand 
This change adds one dependency to [`pom.xml`](https://github.com/xspec/xspec/pull/644/files#diff-600376dffeb79835ede4a0b285078036).

**Comment by AirQuick** [comment]
@cmarchand 
Thanks for the review.

* `MakePath.class` is not what we call a "build helper" in usual applications. `MakePath.class` is used while XSpec is transforming Schematron in `build.xml`.
* Contrary to usual applications, `build.xml` in XSpec is, as you know, not building anything. `build.xml` in XSpec is a runtime driver which works as an alternative to `bin/xspec.bat` and `bin/xspec.sh`.
* In that sense, `MakePath.class` is added to the repository for exactly the same as `XSLTCoverageTraceListener.class`. Without distributing `MakePath.class` with the repository, XSpec users cannot test Schematron until compiling `.java` by themselves.
* I didn't put `MakePath.class` into `java/com/jenitennison/xslt/tests/`, because `MakePath.class` has nothing to do with Coverage support and I'm not sure if we can abuse Jeni's namespace for the other purpose.

Hope this helps.

**Comment by AirQuick** [comment]
@cmarchand 
Maybe you were thinking about Maven when you said "compiled at build time"?
So I removed the dependency from `pom.xml` and excluded `io/xspec/xspec/ant/**`.
#664 which is already merged into this branch will ensure `pom.xml` is not broken.

**Comment by cmarchand** [comment]
Yes, it's the point.
I've forgotten that xspec repo is a "ready-to-use" repo for end users.

In my other projects, git repo contains only sources, and all deliverables are built by maven. That's the reason of my previous comment. I'm not kind of repo that contains built files, but I can live with this.

**Comment by AirQuick** [comment]
> I'm not kind of repo that contains built files, but I can live with this.

Right. This repo is a bit strange. I guess it's just a legacy of the original repo in Google Code. We may change it in the future.

With my latest commits, I confirmed Maven artifacts did not contain `io/xspec/xspec/ant/**`. So I'm merging this.
If anyone comes up with a better solution without Java, it is very much welcome. For now, let's live with this, because it solves a real problem.

**Pull request merged**
