### PR TITLE
feat(xslt): code coverage on Saxon-HE

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request enables Code Coverage on Saxon-HE by replacing `saxon:line-number()` with our own `x:line-number()` (484008f8fee84a942e4391374bfdc6feac9b3fcc).

I'm not familiar with Java, so I looked at [Saxon doc](http://www.saxonica.com/documentation/index.html#!extensibility/integratedfunctions/ext-full-J) and just followed suit.

Besides the automated tests with Saxon-HE on our CI, I tested this with HE (9.9.1.6, 9.8.0.14, 9.8.0.12 and 9.7.0.21), EE (9.9.1.6, 9.9.1.5, 9.8.0.15, 9.8.0.14, 9.8.0.12 and 9.7.0.21) and Oxygen 22.0 (our **XSLT Code Coverage** transformation scenario).

### Test on Azure Pipelines
The automated tests on Azure Pipelines are failing on Windows because of #793, which demonstrates that the automated tests for Code Coverage are working fine. 😀 
Most likely `core.autocrlf` git configuration on Windows in Azure Pipelines is `true`.
Once we merge #794 into `master` and then into this branch, the test failures will be fixed.

### Further work
* Remove [*Requirements*](https://github.com/xspec/xspec/wiki/Code-Coverage#requirements) from Wiki.

### CODE REVIEW

**Comment by AirQuick** [comment]
@galtm 
Can you just check to see if Code Coverage works in your environment? Any Saxon version/edition will do.
You don't necessarily need to review the details.
Unfortunately #746 is not fixed.

**Comment by galtm** [comment]
> Can you just check to see if Code Coverage works in your environment? Any Saxon version/edition will do.

Yes, I was able to generate a code coverage report for `xspec-space_stylesheet.xspec` in Oxygen v22.0 using the transformation scenario in the XSpec framework.

While doing that, I noticed that the report uses a font size that is too small in some browsers. It's not related to this PR, so I will create a separate issue.

**Comment by galtm** [comment]
> While doing that, I noticed that the report uses a font size that is too small in some browsers. It's not related to this PR, so I will create a separate issue.

Created #796

**Comment by AirQuick** [comment]
> Once we merge #794 into `master` and then into this branch, the test failures will be fixed.

Done. Now all tests green.

**Comment by AirQuick** [comment]
Pros
* Code Coverage works on Saxon-HE.
* Code Coverage feature is tested on CI (Windows, Linux, macOS).

Cons (and mitigation factor for each)
* We need to maintain another Java code.
  * But it's tiny and we can revert this squash commit at any time.
* Ant [`xslt/classpath`](https://github.com/xspec/xspec/pull/795/files#diff-2cccd7bf48b7a9cc113ff564acd802a8R476-R479) might possibly be [buggy](https://github.com/xspec/xspec/issues/190#issuecomment-379632848).
  * Even so, it will affect only formatting coverage report HTML.
  * If it turns out to be awful buggy, we will be able to fall back on `<java>`.

**Comment by AirQuick** [comment]
@xspec/xspec 
Considering the [pros and cons](https://github.com/xspec/xspec/pull/795#issuecomment-590094652), I believe the pros clearly outweigh the cons. I'm merging this.

Thanks @galtm for testing this out.

**Comment by AirQuick** [comment]
> ### Further work
> * Remove [_Requirements_](https://github.com/xspec/xspec/wiki/Code-Coverage#requirements) from Wiki.

[Done](https://github.com/xspec/xspec/wiki/Code-Coverage/_compare/e36d0701bb8c5fa45b90550f45174ecbcd0af7db...0105da1aa72fb04c346e54a68da846e405180b6e)

**Pull request merged**
