### PR TITLE
Files for code coverage tutorial

### LINKED ISSUE #196: Update code coverage wiki with dedicated tutorial files
[Wiki](https://github.com/xspec/xspec/wiki/Code-Coverage) demonstrates Code Coverage using `escape-for-regex.xspec` which is not designed to be a coverage example. So "missed" lines in [the picture](https://github.com/xspec/xspec/wiki/images/code-coverage.png) do not make much sense.
There should be a set of dedicated files in `tutorial` directory and we should update Wiki using it.

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request derives from #297. So needs to be handled after that.

---

Fixes #196. Obsoletes #197.

If this pull request is ok and gets merged, I'll replace [the tutorial section of wiki](https://github.com/xspec/xspec/wiki/Code-Coverage#tutorial) with this excerpt

```shell
$ bin/xspec.sh -c tutorial/coverage/demo.xspec
Saxon script not found, invoking JVM directly instead.

Creating Test Stylesheet...

Running Tests...
Collecting test coverage data; suppressing progress report...
****************************************
controller=net.sf.saxon.Controller@d29f28

Formatting Report...
passed: 1 / pending: 0 / failed: 0 / total: 1
Report available at tutorial/coverage/xspec/demo-coverage.html
Done.
```
and this picture

demo

### CODE REVIEW

**Comment by AirQuick** [comment]
This pull request contains a lot of commits for historical reasons, but all that needs to be reviewed is a single commit 75e17ee70b80d557f478b9d4a9fbfd8afba82fea and the proposed changes to Wiki.

**Comment by AirQuick** [comment]
Thanks, @galtm , for the review to move the project forward.

---

> I suppose you may want to get the pull requests up to #297 merged before merging this, right?

Right. Some other pull requests (including #300, #301, #341) depend on this pull request and I have to unify the dependency chain.

**Comment by cirulls** [comment]
I'm going to merge this pull request into `master` when these builds on [AppVeyor](https://ci.appveyor.com/project/xspec/xspec/builds/21216692) and [Travis](https://travis-ci.org/xspec/xspec/builds/471897543) have successfully completed. @AirQuick: feel free to merge the latest `master` in this pull request as you usually do.

**Comment by AirQuick** [comment]
@cirulls
Now that all is green, I merged this and updated [Wiki](https://github.com/xspec/xspec/wiki/Code-Coverage#tutorial) to reflect it.

**Comment by cirulls** [comment]
Thanks for merging and pinging me, I added this to the draft release notes.

**Pull request merged**
