### PR TITLE
Add Oxygen transformation scenario for Code Coverage

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request adds an Oxygen transformation scenario for Code Coverage.

oxy-cc-trans

Running this transformation scenario with XSLT XSpec file generates `[XSpec filename]-coverage.html` in the same directory as the `.xspec` file and opens it in the default Web browser.

We could avoid adding this new transformation scenario and just add the Code Coverage parameters (`xspec.coverage.enabled` (value `false`) and `xspec.coverage.html`) to the existing **Run XSpec Test** transformation scenario. But if we do so, those who want to try Code Coverage have to duplicate the transformation scenario, set `xspec.coverage.enabled` to `true` and update `locationToOpenInBrowserURL` to match `xspec.coverage.html`. That would be tedious, so this pull request provides a transformation scenario dedicated to Code Coverage.

On Oxygen 21.1 on Windows and Linux, I verified that the new **XSpec Code Coverage** transformation scenario worked with `tutorial/coverage/demo.xspec` and `test/xspec-variable_stylesheet.xspec`.

### CODE REVIEW

**Comment by AirQuick** [comment]
I may have named the new transformation scenario badly (**XSpec Code Coverage**). People may expect it to work with Schematron or XQuery, but actually it works only for XSLT. Feedback is welcome.

**Comment by AirQuick** [comment]
Thanks for the review, @galtm 

> About the name, how about "XSLT Code Coverage"?

Took it in c8f21819ba77ab93937cb18925bfed69e15b34ab.

> distinct descriptions of the xspec.coverage.html and xspec.result.html parameters

Updated in 7b45b620e2d6fb2978535893623d6bc08f494e29 and f15b3105b04e386fafd8b55ef84a83f1aedd09b3.

**Comment by galtm** [comment]
> > distinct descriptions of the xspec.coverage.html and xspec.result.html parameters
> 
> Updated in [7b45b62](https://github.com/xspec/xspec/commit/7b45b620e2d6fb2978535893623d6bc08f494e29) and [f15b310](https://github.com/xspec/xspec/commit/f15b3105b04e386fafd8b55ef84a83f1aedd09b3).

Looks good, thanks.

**Comment by AirQuick** [comment]
Thanks @galtm for the review and the suggestions. Merging this.

**Pull request merged**
