### PR TITLE
docs: code coverage behavior by element

### PR DESCRIPTION
**Pull request by galtm**
This pull request adds documentation for XSLT code coverage reporting at a per-element level for most XSLT elements. The main reason it is a repo file rather than a wiki page is so that it can be in the same pull request with code changes (and we anticipate code changes in the code coverage functionality the near future).

Adrian Bird (@birdya22 in GitHub) wrote the document that I committed in c67c0ec4b2119e21cf753931d8a3550535795285; see https://github.com/xspec/xspec/issues/1921#issuecomment-2162786270.

I made some editorial tweaks in 017160c724677f80efa2f4d26863cba2cd7d5122 and then added mention of the Saxon version in 63a2710bff920b5654401837ad6770aa4b5a88ed. Adrian, please let me know if my modifications inadvertently changed the underlying meaning. Feel free to ask me to revert any tweaks you dislike or disagree with.

Follow-up needed: Create issues for the areas where the document says TBD or describes a behavior that isn't what the current implementation does.

### CODE REVIEW

**Comment by galtm** [comment]
@cmarchand : You have experience using the XSLT code coverage reporting feature, so I thought you might be interested in this document and discussions that grow out of it.

**Comment by galtm** [comment]
While the pull request is still open, the rendering is visible at https://github.com/galtm/xspec/blob/code-coverage-by-element-doc/docs/xslt-code-coverage-by-element.md

**Comment by cmarchand** [comment]
Nice job ! And huge job !
I have to spent time on this.

First read tells me that `Categories` are not defined : what is a category.

If you are Ok, I'll add some commit, mainly on styling.

**Comment by birdya22** [comment]
> Adrian, please let me know if my modifications inadvertently changed the underlying meaning. Feel free to ask me to revert any tweaks you dislike or disagree with.

My only comment is in `xsl:stylesheet`.  You added the following in the Comment:

> unless the entire file is unused

Isn't it the case that if the entire file is unused, the coverage report outputs "not used" and doesn't display the stylesheet. 
So is your addition necessary?

**Comment by birdya22** [comment]
> Follow-up needed: Create issues for the areas where the document says TBD or describes a behavior that isn't 
> what the current implementation does.

I can do that. 
I'll start with the ones where the document describes a behavior that isn't what the current implementation does.

**Comment by galtm** [comment]
> Isn't it the case that if the entire file is unused, the coverage report outputs "not used" and doesn't display the stylesheet.
> So is your addition necessary?

It's not strictly necessary, and you are right that in the "not used" case, the report doesn't display the stylesheet. The reason I added that phrase is that "it has to be executed" implicitly assumes that something in the file is executed. Should I restore the original in both cases? Another option could be something like "it has to be executed (unless the entire file is unused, in which case the report doesn't display this element at all)".

**Comment by galtm** [comment]
> I can do that.
> I'll start with the ones where the document describes a behavior that isn't what the current implementation does.

I thought that would be on my task list, but thanks for volunteering! :)  With the extra time, I'll work on switching to the linked tree model with Saxon 12.4, following your suggestion in #1920.

**Comment by cmarchand** [comment]
I come back on Categories and CATEGORY.

First, Categories are defined as "actually CSS class names used on span elements"... Then, on each element, CATEGORY is used on Xslt element, to categorize them according to Xslt specification, and the two words defined really two different things.

Could the first one be changed to "Status" ? Or "Coverage status" ?

Something like

## Coverage status

The following list describes the `Coverage status` used in code coverage. These status are actually CSS class names used on span elements that enclose each node in the coverage report.

- **Hit** - the node was executed
- **Missed** - the node was not executed
- **Ignored** - the node is a declaration and no trace information is provided. Without extensive work in XSpec to parse the stylesheet it is not possible to determine if these declarations are used
- **Unknown** - no trace information is provided about the node when it is executed so it cannot be determined if the node was executed
- **Comment** - this is a comment node (determined by the stylesheet analysis and not the trace output)
- **Whitespace** - this is a whitespace only text node (determined by the stylesheet analysis and not the trace output)

**Comment by birdya22** [comment]
> It's not strictly necessary, and you are right that in the "not used" case, the report doesn't display the stylesheet. The reason I added that phrase is that "it has to be executed" implicitly assumes that something in the file is executed. Should I restore the original in both cases? Another option could be something like "**_it has to be executed (unless the entire file is unused, in which case the report doesn't display this element at all)_**".

I prefer the last option which I highlighted in bold/italic.

**Comment by birdya22** [comment]
> I'll start with the ones where the document describes a behavior that isn't what the current implementation does.

Before I raise new issues I thought I would share the format I have come up with. I'm ok with changing it  if needed. This is the `xsl:context-item` issue and I have indicated where I believe there will be changes to coverage reports. This one is unusual because the change will affect an existing test, but it is the overall format I'm keen for comments on.
I'll wait for some feedback before raising any issues.

CURRENT NON_CONFORMANCE
The xslt-code-coverage-behavior-by-element.md file says that `xsl:context-item` elements should always be marked as 'ignored'.
The current coverage-report.xsl marks them as 'hit' due to a specific rule:
```
<xsl:when test="self::xsl:context-item">
  <!-- Saxon does not seem to call enter() for xsl:context-item (xspec/xspec#1410) -->
  <xsl:sequence select="local:coverage(parent::xsl:template, $module-id)" />
</xsl:when>
```
Was this rule added as a result of external_issue-1410, and does it need to be reviewed?

CHANGES IN COVERAGE-REPORT.XSL
The current rule needs to be reviewed in coverage-report.xsl to ensure `xsl:context-item` elements are always marked as 'ignored'.

CHANGES IN COVERAGE REPORTS
In the coverage report `xsl-context-item-coverage.html` the `xsl:context-item` element will be marked as 'ignored' rather than 'hit'.
In the coverage report external_issue-1410_invoked-empty-coverage.html both `xsl:context-item` elements will be marked as 'ignored'. The first is currently 'hit' and the second 'missed'.

**Comment by galtm** [comment]
Overall, I think the format looks great. Two comments:

1. Is the CHANGES IN COVERAGE REPORTS section meant to describe test updates (e.g., the expected reports in `test/end-to-end/cases-coverage/expected/stylesheet`) or more generally any change that users will see in their coverage reports? If it's only about test updates, then maybe the title should be a little more narrowly focused.
2. I've been refactoring the `coverage-report.xsl` code to make it easier for us to change the behavior where needed. I haven't created the pull request yet, but you can see the changes I have so far, https://github.com/xspec/xspec/commit/578d550a6976cc3710b994c0cce4b08da51e04d8 . I mention this because your format includes code excerpts. Maybe it's fine to keep doing that, and after my changes are finalized and merged I can add comments to your issues to provide newer pointers to the code (such as "The refactored XSLT reaches `XSLT:context-item` in the template for the Use Parent Data rule"). What do you think?

**Comment by galtm** [comment]
> I prefer the last option which I highlighted in bold/italic.

Done, in 48d8ba5e15cdf87a9fb6e793182b05e9c39055ea.

**Comment by birdya22** [comment]
> Is the CHANGES IN COVERAGE REPORTS section meant to describe test updates (e.g., the expected reports in test/end-to-end/cases-coverage/expected/stylesheet) or more generally any change that users will see in their coverage reports? If it's only about test updates, then maybe the title should be a little more narrowly focused.

Yes to the first point. More focused: CHANGES IN TESTS/END-TO-END/CASES-COVERAGE/EXPECTED/STYLESHEET  COVERAGE REPORTS


> I've been refactoring the coverage-report.xsl code to make it easier for us to change the behavior where needed. I haven't created the pull request yet, but you can see the changes I have so far, https://github.com/xspec/xspec/commit/578d550a6976cc3710b994c0cce4b08da51e04d8 . I mention this because your format includes code excerpts. Maybe it's fine to keep doing that, and after my changes are finalized and merged I can add comments to your issues to provide newer pointers to the code (such as "The refactored XSLT reaches XSLT:context-item in the template for the Use Parent Data rule"). What do you think?

I'm happy not to include the excerpt but just says there is a specific rule currently and leave it at that (just as an indicator when looking at the code) .

I will have a look at your refactoring later.

**Comment by galtm** [comment]
> Categories and CATEGORY

@cmarchand, I agree with your suggestion to avoid using the word category to mean both the coverage category and the XSLT element category. I'm happy with either "coverage status" or "coverage category". @birdya22, what do you think?

**Comment by galtm** [comment]
> Yes to the first point. More focused: CHANGES IN TESTS/END-TO-END/CASES-COVERAGE/EXPECTED/STYLESHEET COVERAGE REPORTS

@birdya22 : Thanks for clarifying what you meant. That's a lot of text in all-caps, and it almost looks like the slashes could mean a conjunction between words rather than a file path separator.

What if you use Markdown headings instead of all-caps, like the following?
```
### Changes in `test/end-to-end/cases-coverage/expected`
```

Rendering looks like this:

### Changes in `test/end-to-end/cases-coverage/expected`

(I dropped the "stylesheet" directory name because it's the only directory in "expected".)

---

> I'm happy not to include the excerpt but just says there is a specific rule currently and leave it at that (just as an indicator when looking at the code) .

If you have the code right in front of you, pasting it into the issue will probably be helpful. If you'd have to do research to find the relevant code, leaving it out is fine (it's up to you).

**Comment by galtm** [comment]
Comments, whitespace-only text nodes, and processing instructions also use the "ignored" CSS class in the current implementation. Were you thinking that the CSS class usage should change to match the list in the document, even if the ignored (for declarations), comment, whitespace, and pi CSS classes have the same style definition? If not, it's probably better not to tie the list of coverage types to the CSS classes.

Just brainstorming in case anything strikes you as promising: coverage type, coverage value, coverage classification

**Comment by galtm** [comment]
I'm OK with updating the coverage report XSLT to make a one-to-one correspondence between CSS class names and coverage status values. (Not as part of this documentation pull request but as part of some other pull request.) I like your other comment (https://github.com/xspec/xspec/pull/1934#issuecomment-2176548604) and want to come back to it after some other tasks are done.

I like "coverage status" better than "coverage class" because in the context of the document in this pull request, I think the primary goal is to document the logic of how we determine which nodes are hit, missed, etc. Whether the CSS classes are well named to match the logic seems secondary.

If you're OK with "coverage status" I'll update the file in this pull request to use that term. If you feel strongly about "coverage class" I'll update the file to use that term.

**Comment by galtm** [comment]
> Yes I was thinking that the CSS class usage should change to match the list in the document.

I created #1956.

I put the rest of your comment in #1957 because I thought putting too many ideas into one issue might get confusing, especially if one idea is fairly well-defined and others are less straightforward. Not sure if that was the right decision, but we will see.

**Comment by galtm** [comment]
I'll merge this pull request after checks are complete. We can continue refining the document in future pull requests, considering it a living document.

**Pull request merged**
