### PR TITLE
feat(schema): add Schematron schema for XSpec

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request adds a Schematron schema for XSpec document (`src/schemas/xspec.sch`) and integrates it to Oxygen framework (`xspec.framework`).

At this time, the schema just detects suspicious whitespace-only text nodes in user content and proposes some [Quick Fixes](https://www.oxygenxml.com/doc/versions/21.1/ug-editor/glossary/quick-fix.html).

xspec-sch

Not sure if this particular schema is useful. But this change could be a placeholder for other future enhancements.

### How I tested it

Aside from the automated `test/xspec-sch.xspec`, I tested SQF briefly on Oxygen 21.1 on Windows and Linux.

### CODE REVIEW

**Comment by galtm** [comment]
@AirQuick , do you think the following is a mistake or a legitimate style preference? The text node is going to be ignored whether it's white space only or not, won't it?

```
<x:expect label="Boolean test with closing tag on next line" test="true()">
</x:expect>
```

By trying out your schema, I found a few instances of this pattern in my code. I would not call them a deliberate style preference on my part, and I wouldn't mind seeing the warning and deleting the white space. However, it made me wonder whether anyone does that on purpose, routinely, knowing the white space is ignored.

**Comment by AirQuick** [comment]
> do you think the following is a mistake or a legitimate style preference? The text node is going to be ignored whether it's white space only or not, won't it?

May be a mistake or may be intentional. Unfortunately it's ambiguous. It cannot be judged statically. But, at least, I think we should discourage writing in that style.

The root cause of the ambiguity is that `@test` has dual functions and its functionality is determined at run time. In other words, XSpec schema cannot know whether `@test` will work as a boolean assertion or will work as a context selector.

XSpec v0.4.0-rc tried tackling the ambiguity by defining `x:expect/@assert` and `x:expect/@context`, but it had been removed because of its some fundamental flaws.

I have another proposal to tackle the ambiguity again. My proposal will define XSpec schema v2 (`/x:description/@version` = `2.0`) where you are required to rewrite `<x:expect test="[ambiguous test]" />` to either `<x:assert test="[boolean assertion]" />` or `<x:expect select="()" test="[context selection]" />` depending on your actual intention. I have its initial implementation and a companion Schematron schema which helps the users to migrate to v2. I developed it more than a year ago, so I'm forgetting its details, but discouraging `<x:expect test="[boolean assertion]">[ignorable nodes]</x:expect>` will surely help migrating to v2 (or any other similar proposals to tackle the ambiguity).

**Comment by galtm** [comment]
> will surely help migrating to v2

Thanks for your thoughts on this. If the warning and quick fix help people migrate, then that's an answer to someone who might initially say, "this warning creates noise in my validation pane and wastes my time for no reason." I am on board with it being classified as a warning.

I look forward to seeing more about v2, when you have something ready to share. :) (Did you consider more drastic changes, such as changing the attribute names on `x:expect`?)

**Comment by AirQuick** [comment]
@xspec/xspec 
While working on this pull request and another, I found it would be nice to have `schema` scope, primarily for [`src/schemas/`](https://github.com/xspec/xspec/tree/master/src/schemas).
So I added 4df5204659d09cde4713c2a45697c9d0c42d637b to this pull request.

**Comment by AirQuick** [comment]
Thanks @galtm for looking into this. I'm resuming.

> Is it OK that `test/end-to-end/cases/schematron-023.xspec` has an instance of this warning?

The whitespace-only text node is ignored and not necessary. (What's important there is the element name.)
I removed it in 0bfdbc736b87099eeb53a56a84cbaa4397d6ea42.

> It would be nice to have a comment in `xspec-space.xspec` and `xspec-space_stylesheet.xspec` such as, "When modifying this file, check whether xspec-sch.xspec needs any additions or updates."

I should have done it in the first place. Added it in f1dab868210d47b858e10e5aff3a0615dcd1b495.

**Comment by AirQuick** [comment]
> I look forward to seeing more about v2, when you have something ready to share. :) (Did you consider more drastic changes, such as changing the attribute names on `x:expect`?)

If we split `<x:expect test="[ambiguous test]" />` into `<x:assert test="[boolean assertion]" />` and `<x:expect select="()" test="[context selection]" />`, `x:expect/@test` may be better renamed to `@context` or something else. But I'm not sure right now.

**Comment by AirQuick** [comment]
Tested on Oxygen 22.0.

@galtm
Are you fine with merging this?

**Comment by galtm** [comment]
@AirQuick , I'll take another quick look at this tonight and get back to you soon.

**Comment by galtm** [comment]
@AirQuick , Yes, this looks good. Ready to be merged. Sorry for my delay.

**Comment by galtm** [comment]
> If we split `<x:expect test="[ambiguous test]" />` into `<x:assert test="[boolean assertion]" />` and `<x:expect select="()" test="[context selection]" />`, `x:expect/@test` may be better renamed to `@context` or something else. But I'm not sure right now.

Sounds like a good direction to pursue.

**Comment by AirQuick** [comment]
Merged.

Thanks, @galtm for reviewing this.

@AlexJitianu 
Just FYI. We now have SQF for XSpec integrated in `xspec.framework`. Right now, it doesn't provide advanced features. It just detects suspicious whitespace-only text nodes.

**Pull request merged**
