### PR TITLE
docs: add contributing guidelines

### PR DESCRIPTION
**Pull request by cirulls**
## Summary

Following discussions in #622, I submit an initial draft containing guidelines on how to contribute to XSpec. The main focus is to highlight how to contribute to XSpec and to document conventions for git commit messages once Commit Lint checks are configured to the xspec repository (see #622). 

Few notes/remarks:

- Once/if this pull request is merged into `master`, a link to `CONTRIBUTING.md` should automatically appear when a new issue or pull request is raised (see [here](https://github.blog/2012-09-17-contributing-guidelines/#contributors-wanted-inquire-within)).
- Once/if this pull request is merged into `master`, it would be good to put a link to `CONTRIBUTING.md` inside `README.md`.
- Once/if this pull request is merged into `master` and Commit Lint is configured in the xspec repo, I guess pull requests automatically raised by dependabot will not comply with the git commit conventions. The git commit message could be amended before hitting the squash merge but it would be nice if dependabot could submit the git message prefixed with the correct type (I have not investigated yet if it is possible).  
- I took inspiration from the [Atom contributing guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md) which contains many other ideas to add in the future. For example, it would be good to write down a code of conduct and to add other code conventions related to formatting, use of tabs and white-space, etc.

Feel free to suggest changes and future improvements.

### CODE REVIEW

**Comment by AirQuick** [comment]
Thanks @cirulls 
I'll be free after 17 Jan and will look into this then.
After we agree to the convention, are you going to implement [Commit Lint](https://www.commit-lint.com/)?

**Comment by cirulls** [comment]
Thanks @AirQuick. Absolutely, after agreeing on a convention for commit messages I will enable Commit Lint on this repository.

**Comment by AirQuick** [comment]
As for the commit subject, `!` for a breaking change (discussed in [Conventional Commits](https://www.conventionalcommits.org/)) might be handy. Do you know whether it fits nicely in the tool chain we're going to use?

**Comment by AirQuick** [comment]
Based on this proposal, I updated my pull request titles: https://github.com/xspec/xspec/pulls/AirQuick
While working on it, I realized it would probably be nice to have `oxygen` scope for describing Oxygen integration.

**Comment by AirQuick** [comment]
> * The git commit message could be amended before hitting the squash merge but it would be nice if dependabot could submit the git message prefixed with the correct type (I have not investigated yet if it is possible).

Looks like it's possible: https://twitter.com/dependabot/status/1144204566654849024

**Comment by AirQuick** [comment]
> Looks like it's possible: https://twitter.com/dependabot/status/1144204566654849024

According to its corresponding [doc](https://dependabot.com/docs/config-file/#commit_message), `include_scope: true` generates commit prefixes with `deps` scope. So I'd suggest adding `deps` to our scope list.
We can use the `deps` scope for decorating other types. e.g. #747 would be `ci(deps)`.

**Comment by AirQuick** [comment]
#759 suggests that `basex` scope would be useful.

**Comment by cirulls** [comment]
@AirQuick: thanks for your feedback. I added `oxygen`, `basex`, and `deps` as scopes in be85a1a.

Regarding breaking changes, flagging them with `!` after the type/scope as suggested in the link you sent is a very good idea, it will allow to higlights major changes in the code base. 

> Do you know whether it fits nicely in the tool chain we're going to use? 

It looks like there is an open pull request in Commit Lint to support the `!` notation for breaking changes: https://github.com/conventional-changelog/commitlint/issues/658  Once that feature is available in Commit Lint, it would be good to update the `CONTRIBUTING.md` page and start using the `!` notation when applicable.

Regarding the commit messages for Dependabot, I committed the configuration for setting up automatic commit messages for Dependabot in cc7b31a. The commit message from PR raised by Dependabot should appear as `build(deps)` (I chose build as title as Dependabot PRs always refer to the `pom.xml` file but I'm happy to consider other suggestions for the commit message). I've not tried to see if it works and I guess we can only test it properly by merging this branch into `master`and observing the new PRs raised by Dependabot. I guess I can test it first by creating a dummy repository outside XSpec if we don't want to pollute the master branch, let me know if you prefer me to do so.

**Comment by cirulls** [comment]
@AirQuick: thanks for your review, I'm going to merge this PR into `master`. After that, I will work on the following:

1. Set up Commit Lint for the xspec repository.
2. Create a pull request to add the link to `CONTRIBUTING.md` in `README.md`.
3. Observe Dependabot PRs to see if they come up with the correct commit message (thanks for the validation link, I didn't know about it).

**Comment by cirulls** [comment]
When I merged this pull request, three builds on Travis failed with the following error message:

```
SAXON_JAR is not found

The command "./test/ci/print-env.sh && ./test/ci/run-codespell.sh && ./test/ci/run-core-tests.sh && ./test/ci/maven-package.sh -q && ./test/ci/compile-java.sh -silent && ./test/ci/last-git-status.sh

" exited with 1.
```
This is the same temporary issue that occurred [here](https://github.com/xspec/xspec/pull/757#issuecomment-572106700). As usual, I just replayed the jobs in Travis and the builds went back to green.

**Comment by AirQuick** [comment]
> This is the same temporary issue that occurred [here](https://github.com/xspec/xspec/pull/757#issuecomment-572106700). As usual, I just replayed the jobs in Travis and the builds went back to green.

Looks like some Travis CI IP addresses are blocked: https://github.com/travis-ci/travis-ci/issues/10053#issuecomment-579983072

**Comment by cirulls** [comment]
Thanks for digging this out, I guess there isn't much we can do to prevent it as it depends on Sonatype and Travis. As a workaround, we can replay the job in case it happens again.

I set up Commit Lint for the xspec repository, the configuration is under https://github.com/xspec/xspec/settings/installations and is visible only to XSpec maintainers. There is now an additional check when a pull request is submitted:

image

I wonder if we should make this check required like the Travis and Azure Pipelines checks. @AirQuick: what do you think?

When creating the pull request I'm also presented with a reminder about the contributing guidelines:

image

**Comment by AirQuick** [comment]
> I wonder if we should make this check required like the Travis and Azure Pipelines checks. @AirQuick: what do you think?

Agreed. In [Branch Protection Rules](https://github.com/xspec/xspec/settings/branches), I marked `commit-lint-pr` as required. Let's see what happens.

**Comment by AirQuick** [comment]
> * [ ]  Observe Dependabot PRs to see if they come up with the correct commit message (thanks for the validation link, I didn't know about it).

Confirmed (#812)

**Pull request merged**
