### PR TITLE
Prefix "init" and "compile" in 'depends'

### PR DESCRIPTION
**Pull request by tgraham-antenna**
`init` and `compile` are a common target names.

`depends="init"` runs the `init` target in the importing build file, whereas `depends="xspec.init"` runs the `init` target in the `xspec` build file.  Similarly for `compile`.

Conceivably, every target name in a `depends` in XSpec's `build.xml` should be prefixed with the `xspec` build name, but `init` and `compile` are the two most likely to be accidentally overridden by an importing build file.

### CODE REVIEW

**Comment by AirQuick** [comment]
> `init` and `compile` are a common target names.

Right. I think that's why `build.xml` uses the current names.
If it's common, why XSpec alone should not use the common names?
Isn't it the importer's responsibility to manage names?

**Comment by tgraham-antenna** [comment]
I found this with a `build.xml` that has an `init` target that I modified to import XSpec's `build.xml` so that I could run XSpec on some existing Schematron.  Without modification, XSpec's `compile` target was running the importing build file's `init` target.  Needless to say, it did not initialise the right things.

Unfortunately, fortunately, or by design, the recognising of targets prefixed with the build file's `name` attribute value only applies when importing is happening, which is why the unit tests failed and why I've been thrashing around trying to get them to pass again.

**Comment by AirQuick** [comment]
Why don't you use `include` and rely on automatic prefixing, if you're not overriding?

**Comment by AirQuick** [comment]
With this pull request, the following code which used to work fine relying on automatic prefixing

```xml
    <include file="build.xml"/>

    <target name="test">
        <antcall target="xspec.init"/>
    </target>
```

now has to be modified to

```xml
        <antcall target="xspec.xspec.init"/>
```

which looks weird. Is this the way things should usually work in Ant ecosystem?

**Comment by tgraham-antenna** [comment]
Too much `xsl:include` vs `xsl:import` in my past, I think.

The XSpec wiki currently suggests `import` (possibly from the same biases).

Based on your most recent comment, the wiki (and my build file) should be changed, rather than changing `build.xml`.

**Comment by AirQuick** [comment]
Can you try `include` and let us know if it solves your problem?

And indeed `test/**/build*.xml` uses `import`. I don't know why. 😅 Maybe just followed Wiki.
If `include` works for you, I'll try replacing `test/**/build*.xml` with `include` to see if it works there. If it works, Iet's update Wiki.

**Comment by tgraham-antenna** [comment]
I don't know how it ever worked.  `include` fails with:

````
C:\xspec-1.4.0\build.xml:486: The following error occurred while executing this line:
Target "fail" does not exist in the project "...". 
````

#668 gets past that problem.

**Comment by AirQuick** [comment]
Thanks for spotting it!
I guess the `antcall` in question was introduced while merging oXygen's code in haste. Looks like we'd better have some basic tests both for `import` and `include`.

**Comment by AirQuick** [comment]
> we'd better have some basic tests

Will be followed up in #669

**Comment by AirQuick** [comment]
> the wiki (and my build file) should be changed

Wiki will be handled as well in #669.

**Comment by tgraham-antenna** [comment]
@AirQuick's comment at https://github.com/xspec/xspec/pull/666#issuecomment-538002513 shows that the current PR makes some usage too unwieldy.

With the change from #668, my project works okay with `include`.

#669 is expected to document the best way to use `import` to import the XSpec build file.

**Pull request closed without merging**
