### PR TITLE
Integrate Oxygen framework

### PR DESCRIPTION
**Pull request by AirQuick**
This pull request introduces an Oxygen [framework](https://www.oxygenxml.com/doc/versions/21.1/ug-editor/glossary/framework.html).
As a starting point, this pull request takes Oxygen 21.1's built-in XSpec framework settings as it is.

### Why

[Wiki](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen) lets you use the latest Ant build file on Oxygen. But this repository has other latest components including these:

* RelaxNG schema
* XProc harness
* Schematron schema (possibly in the near future: #695)

They do not take effect on Oxygen until you configure a framework.

### How to use

Just open `xspec.xpr` on Oxygen as a project. This enables the project-specific framework for XSpec (`xspec.framework`).

### Commits
* 77cd32015a078ce714de370d89bf37cc382017d9 creates an empty Oxygen project file at the root of the repository.
* cef7a419c9ddc08c0826feb49713c981661f2c4e enables a project-specific framework for XSpec:
  * Move `xspec.framework` from `editor/oxygen/` to the repository root. This relative location aligns with Oxygen's built-in XSpec framework (`[Oxygen install dir]/frameworks/xspec/`) directory structure.
  * Enable [**Project Options**](https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/preferences-storing.html) in Preferences - Document Type Association - [Locations](https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/framework-location.html).
  * Add [`${pd}`](https://www.oxygenxml.com/doc/versions/21.1/ug-editor/topics/editor-variables.html) to **Additional frameworks directories**.
* bada4425d0de5076a9312e496efcb1f36c6a3006 copies the framework settings from the latest Oxygen
* 844a324121abc97e7d9df8dd82a56b677d56cec6 deletes [editors/oxygen/](https://github.com/xspec/xspec/tree/91bd679dd603caa8d0b07b84b74a13f5f94b4909/editors/oxygen) because it is stale and no longer necessary

### Test

I manually verified the followings on Windows and Linux:
* RelaxNG schema takes effect. (`x:variable` and `@catch`)
* **Run XSpec Test** and **XSpec for XSLT using XProc** transformation scenarios work

### Further work
Update [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen) to direct the reader to use `xspec.xpr`.

### CODE REVIEW

**Comment by AirQuick** [comment]
@xspec/xspec
@AlexJitianu
I'll merge this some time later this week unless a concern arises.

Soon after that, I'll probably submit these changes:
* Add a descriptor file to publish some v1.5.0 prerelease snapshots as an oXygen [add-on](https://www.oxygenxml.com/addons.html)
* Enhance **Run XSpec Test** transformation scenario to include XQuery
* Add **XSpec Code Coverage** transformation scenario
* Fix **XSpec for XSLT using XProc** transformation scenario
* Add **XSpec for XQuery using XProc** transformation scenario
* Add a Schematron schema for XSpec

**Comment by AirQuick** [comment]
Revised [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen) in view of this change. Feel free to correct technical/linguistic errors directly or edit further.

**Comment by AirQuick** [comment]
> ### Further work
> Update [Wiki](https://github.com/xspec/xspec/wiki/Running-with-Oxygen#running-the-latest-version-of-xspec-with-oxygen) to direct the reader to use `xspec.xpr`.

Done.

**Comment by AirQuick** [comment]
@AlexJitianu
From now on, I think SyncRO Soft can just copy these folders/files to `${frameworksDir}/xspec` when bundling XSpec.

* `java/`
* `src/`
* `templates/` (coming soon)
* `build.xml`
* `LICENSE`
* `xspec.framework`

**Comment by dorinajitianu** [comment]
That's great! It all looks good. The next Oxygen release is due to happen mid February so I will probably have to update the bundled version of XSpec at least one month before that. When is the next XSpec release supposed to happen?

**Comment by AlexJitianu** [comment]
That's great! It all looks good. The next Oxygen release is due to happen mid February so I will probably have to update the bundled version of XSpec at least one month before that. When is the next XSpec release supposed to happen?

**Comment by AirQuick** [comment]
@AlexJitianu 
We've put an effort to keep `master` clean and tested (especially thanks to @galtm 's review). So I think we can be flexible as to when we release it. In #744, we'll make sure the release will happen well before Oxygen.

**Comment by galtm** [comment]
Here are some comments and questions about the wiki. (I have some editorial-type changes in mind, too, and I will go ahead and make them with the understanding that you can revert them or modify them further if you want.)

I like that the description of each approach indicates the effect on your Oxygen environment, because that could help people decide. I also like that the non-recommended approach is last and is clearly labeled as not recommended.

Correct me if wrong, but wouldn't "Loading XSpec via Oxygen Project" still work if step 2 said, "In Oxygen, open your existing project file, if you have one, or create a new project file by selecting Project - New Project"? I think that would broaden the applicability of this approach significantly, because users who have a project file for whatever code they're testing will want to integrate the latest XSpec into _that_ project instead of using an XSpec-specific project file. They're likely to be writing code and writing/running tests at the same time.

In "Configuring XSpec Transformation Scenario" between steps 7 and 8, is it worth saying something like, "If you normally customize the standard Run XSpec Test scenario, such as to specify additional libraries, JVM options, or saxon.custom.options, do that now."? If you think the addition would be distracting, it's fine to leave it out.

**Comment by AirQuick** [comment]
Thanks @galtm for editing Wiki. Looks very nice.

> "Loading XSpec via Oxygen Project" still work if step 2 said, "In Oxygen, open your existing project file, ...

> In "Configuring XSpec Transformation Scenario" between steps 7 and 8, is it worth saying something like, "If you normally customize...

Good point indeed. Made changes accordingly. ([diff](https://github.com/xspec/xspec/wiki/Running-with-Oxygen/_compare/3d0d6ae65add429321699a9ef7686ad7bad9a37a...bebc75947eaab47a33c1124956e6cb72402078a6))

**Comment by galtm** [comment]
Great, thank you!

**Comment by cirulls** [comment]
> The next Oxygen release is due to happen mid February so I will probably have to update the bundled version of XSpec at least one month before that. When is the next XSpec release supposed to happen?

@AlexJitianu: XSpec v1.5.0 is now officially out: https://github.com/xspec/xspec/releases/tag/v1.5.0

**Pull request merged**
