### PR TITLE
Add documentation for Schematron support

### PR DESCRIPTION
**Pull request by cirulls**
## Summary
This pull request addresses #128 and adds documentation for Schematron support in XSpec.

## What has changed
I added the following pages on the wiki:

- [Getting-Started-with-XSpec-and-Schematron](https://github.com/xspec/xspec/wiki/Getting-Started-with-XSpec-and-Schematron): this is a tutorial to get started quickly with the first XSpec test for Schematron. The content is mainly taken from the [slides](https://github.com/xspec/xspec/files/961629/Schematron.XSpec.pptx) and the [first tutorial example](https://github.com/xspec/xspec/tree/master/tutorial/schematron).
- [Writing-Scenarios-for-Schematron](https://github.com/xspec/xspec/wiki/Writing-Scenarios-for-Schematron): this is taken from the [documentation](https://github.com/xspec/xspec/blob/master/tutorial/schematron/schematron.txt) provided by @vincentml. I converted it in Markdown and made some minor cosmetic changes in order to standardize it with the existing XSpec documentation. 

I removed [schematron.txt](https://github.com/xspec/xspec/blob/master/tutorial/schematron/schematron.txt) from the code base as this is now part of the wiki (@vincentml suggested to do this in https://github.com/xspec/xspec/pull/105#issue-213627245). I also fixed a typo in a tutorial file. 
   
## How to review

Follow the step-by-step instructions in [Getting-Started-with-XSpec-and-Schematron](https://github.com/xspec/xspec/wiki/Getting-Started-with-XSpec-and-Schematron) and see if you get the expected results. I personally find it super easy to try out this new functionality thanks the documentation provided by @vincentml.

@vincentml: can you check I have not introduced any mistake in the documentation? 
If anyone else wants to try the documentation and suggest changes or improvements, please post your comments.  

## Questions

@vincentml: While following your documentation, I stumbled across these two issues:

1. When I execute the test with the `-s` option using the shell script, the output gives me these following warnings:

```
Compiling the Schematron...
Warning at xslt:stylesheet on line 130 column 3 of iso_dsdl_include.xsl:
  Running an XSLT 10 stylesheet with an XSLT 20 processor
Warning at xslt:stylesheet on line 88 column 8 of iso_abstract_expand.xsl:
  Running an XSLT 10 stylesheet with an XSLT 20 processor
Warning at xsl:stylesheet on line 158 column 2 of iso_svrl_for_xslt2.xsl:
  Running an XSLT 10 stylesheet with an XSLT 20 processor
```
I used Saxon 9.7 HE which is obviously an XSLT 2.0 processor. These warnings cleary come from the Schematron files included in the code base, the files in the output are all stylesheets XSLT 1.0. Do you get the same warnings? Is it safe to ignore them and, if so, is there a way to remove them from the output? 

2. At the end of the process I get the following files: 
    - demo-01-result.html
    - demo-01-result.xml
    - demo-01.xsl
    - demo-01-sch-compiled.xsl
    - demo-01-sch-temp1.xml
    - demo-01-sch-temp2.xml
    - demo-01-var.txt

    I wonder if it would be more elegant to remove the last 4 files at the end of the process since these are clearly temporary files generated during the compilation process. However, I understand that these can be very useful for debugging especially now that the feature has just been released. Is there a specific reason for keeping them?

### CODE REVIEW

**Comment by vincentml** [comment]
Thanks @cirulls :) I'll read through the documentation in detail soon.

In regard to your questions:

1, The "Running an XSLT 10 stylesheet with an XSLT 20 processor" messages do come from the ISO Schematron XSLTs which are written for XSLT 1.0. One option is to redirect the warning message, which could be done in xspec.bat by "2>nul" (and possibly "2>/dev/null" in xspec.sh). Another option would be to update the Schematron stylesheets to XSLT 2.0. A potential third option would be to find out if there is a newer Schematron XSLT reference implementation available.

2. The files are helpful for debugging, but perhaps could be removed by a cleanup routine at the end of xspec.bat and xpec.sh. I've started adding a cleanup routine.

**Comment by cirulls** [comment]
These files seem to be available only in XSLT 1.0 in the [official Schematron repository](https://github.com/Schematron/schematron/tree/master/trunk/schematron/code), I could not find an implementation that uses all the stylesheets in XSLT 2.0. Maybe is it worth posting a feature request on their GitHub? Converting the Schematron stylesheets to XSLT 2.0 would be great but I don't know how much work is involved and it may be something that I would leave to Schematron experts - you may be one though!

Maybe for now it's better to redirect the warning to null, if you do it in the batch script I can replicate it in the shell script. Not ideal as this can remove some useful error message but better than seeing these warnings, I find these warnings can be confusing for new users.

**Comment by AirQuick** [comment]
> 1, The "Running an XSLT 10 stylesheet with an XSLT 20 processor" messages do come from the ISO ...

Yet another option would be adding `-versionmsg:off` to the "Compiling the Schematron" command lines.

**Comment by vincentml** [comment]
That looks like the best immediate option. Thanks for the hint!

**Comment by cirulls** [comment]
@vincentml, I gave you write access to the repository so you should now be able to edit the wiki directly. 

As you now have write access to the XSpec repository as well, please use this power wisely ;-) This mainly boils down to: 
- do not push changes directly to ```master```. Work on your branch and use the pull request mechanism instead
- be kind to others ;-)

**Comment by vincentml** [comment]
Thank you @cirulls ! I will use this ability with care.

I have made a few edits to the Schematron pages in the wiki.

**Comment by vincentml** [comment]
@cirulls, is it now okay to merge this pull request with master?

**Pull request merged**
